### ISSUE TITLE
Limiter doesn't seem to work

### ISSUE THREAD

**Issue by dmontauk** [buger/gor#117]
When I run without the limiter I get this:
ubuntu@HOSTNAME:~$ ./gor --stats --input-file=java-bidder.log --output-http="$WEBSERVER"
Version: 0.8
2014/09/25 18:39:52 output_http:latest,mean,max,count,count/second
2014/09/25 18:39:52 output_http:0,0,0,0,0
2014/09/25 18:39:52 Cannot parse request GET /
��� malformed HTTP request "GET /"
2014/09/25 18:39:57 output_http:100,99,100,1223,244
2014/09/25 18:40:02 output_http:100,99,100,887,177
2014/09/25 18:40:07 output_http:100,99,100,885,177
2014/09/25 18:40:12 output_http:100,99,100,1020,204
When I run it with the limiter:
ubuntu@HOSTNAME:~$ ./gor --stats --input-file=java-bidder.log --output-http="$WEBSERVER|100"
Version: 0.8
2014/09/25 18:41:38 output_http:latest,mean,max,count,count/second
2014/09/25 18:41:38 output_http:0,0,0,0,0
2014/09/25 18:41:38 Cannot parse request GET /
��� malformed HTTP request "GET /"
2014/09/25 18:41:43 output_http:90,89,90,300,60
2014/09/25 18:41:48 output_http:0,0,0,0,0
2014/09/25 18:41:53 output_http:0,0,0,0,0

**Comment by buger** [comment]
For sure you need to check latest version
