### ISSUE TITLE
A way to not replay certain requests when they match a pattern - blacklist

### ISSUE THREAD

**Issue by zetzer** [buger/gor#134]
Since creating a RegExp, which would 'match' if the text does not contain some pattern, is really cumbersome, an option for putting some patterns on a black list would be desired. (One could use 'look-arounds' with (?!pattern)-syntax, but unfortunately it seems not to be supported in golang).
An option like --output-http-url-regexp-negative could be useful. Meaning: URL, which matches such pattern would NOT be replayed. This of course should also work together with --output-http-url-regexp (kind of white list) - the precedence could be: what is forbidden, is more important than what is allowed.

**Comment by buger** [comment]
Negative lookahead can be re-writen in regular regexp rules, example:

`BBB(((?!BBB).)*)EEE` is equal to `BBB([^B]|B[^B]|BB[^B])*EEE`. Can you try it?

**Comment by zetzer** [comment]
My case is: I need to accept, when a string does not contain some word. For RegExp this could mean: some characters at the beginning, forbidden pattern, some characters at the end. So I don't have any arbitrary pattern at the beginning (your's BBB) or any arbitrary pattern at the end (your's EEE). So I've translated your example into ([^B]|B[^B]|BB[^B])*. This does:
1. not accept BBB -> OK
2. accept aBBa -> OK
3. not accept aBBBa -> OK
4. not accept aaB or aaBB -> not OK
So I came up with extended version ([^B]|B[^B]|BB[^B]|[^B]B|[^B]BB)*, which covers case 4. but
5. does not accept BBaB -> not OK

So it is really hard to find a good workaround. But in reality I need to exclude a string containing 15 characters. Imagine the pattern. And what if I need to exclude other blacklisted words - and I all this need to express in one pattern. I'm doomed.

**Comment by buger** [comment]
Got it, i will think what i can do.

**Comment by buger** [comment]
@zetzer well it too long time, but `--http-disallow-url` option added in this pull request https://github.com/buger/gor/pull/165 :)
