### ISSUE TITLE
Panic: runtime error

### ISSUE THREAD

**Issue by garthgoodson** [buger/gor#137]
Command line (forwarding from one machine to another):
sudo ./gor --input-raw :8888 --output-http "http://xxxxxx:8888/xxxxx"

Version: 0.9.2
2015/02/14 04:27:04 Received packet with same sequence
2015/02/14 04:27:04 Received packet with same sequence
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40531c]

goroutine 350411 [running]:
runtime.panic(0x699d20, 0x9eb128)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.ParseRequest(0xc210a08000, 0xc038, 0xc038, 0x0, 0x7f1f393756d8, ...)
        /home/ubuntu/go/src/github.com/buger/gor/output_http.go:37 +0x10c
main.(*HTTPOutput).sendRequest(0xc210065180, 0xc2107661b0, 0xc210a08000, 0xc038, 0xc038)
        /home/ubuntu/go/src/github.com/buger/gor/output_http.go:182 +0x4f
main.(*HTTPOutput).Worker(0xc210065180)
        /home/ubuntu/go/src/github.com/buger/gor/output_http.go:137 +0xfb
created by main.(*HTTPOutput).WorkerMaster
        /home/ubuntu/go/src/github.com/buger/gor/output_http.go:115 +0x65

goroutine 1 [select]:
main.Start(0x0)
        /home/ubuntu/go/src/github.com/buger/gor/emitter.go:14 +0x131
main.main()
        /home/ubuntu/go/src/github.com/buger/gor/gor.go:48 +0x1a4

goroutine 3 [chan receive]:
main.(*RAWInput).listen(0xc210048fa0, 0x7fff87e1b963, 0x5)
        /home/ubuntu/go/src/github.com/buger/gor/input_raw.go:45 +0x20e
created by main.NewRAWInput
        /home/ubuntu/go/src/github.com/buger/gor/input_raw.go:20 +0x7f

goroutine 4 [chan receive]:
main.(*HTTPOutput).WorkerMaster(0xc210065180)
        /home/ubuntu/go/src/github.com/buger/gor/output_http.go:113 +0x34
created by main.NewHTTPOutput
        /home/ubuntu/go/src/github.com/buger/gor/output_http.go:106 +0x2f2

**Comment by joekiller** [comment]
output-http should be top level only (take off the /xxxxxx).  I assume it
isn't but also, ensure your target isn't the same as the source.

**Comment by garthgoodson** [comment]
Sorry, copied the command line wrong.  It is only on top level.

**Comment by garthgoodson** [comment]
I should also add, that it ran for about a day correctly before the panic.

**Comment by joekiller** [comment]
Curious. Any other errors leading up to that or did it just dump?

**Comment by garthgoodson** [comment]
Nope, nothing else.  The other end is still running fine, so no issue there.  Unfortunately, I didn't have coredumps enabled.

**Comment by joekiller** [comment]
Ah I see the rest in the original.  Seems like it died on a post.  Could
have had an error getting the body and we didn't handle it well.  Just a
guess for now.

**Comment by garthgoodson** [comment]
There are some cases when our stream has a closed connection (initiated by the server) midway through a post, resulting in incomplete data for that post.

**Comment by wmoss** [comment]
I think this should at least keep the process from panicing and just print and error and ignore the packet:
 https://github.com/buger/gor/pull/140

**Comment by buger** [comment]
#140 merged

**Comment by buger** [comment]
I'm closing, because it should be for sure fixed in latest versions
