### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by joncooper** [buger/gor#146]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with gor. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable gor on @Sourcegraph by going to https://sourcegraph.com/github.com/buger/gor and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by buger** [comment]
Done!
