### ISSUE TITLE
mention CAP_NET_RAW as alternative to sudo

### ISSUE THREAD

**Issue by MartinNowak** [buger/gor#147]
For input-raw it's sufficient to give CAP_NET_RAW capabilities to gor, it's not required to run the program as root.

```sh
sudo setcap CAP_NET_RAW=ep gor
```

[capabilities(7): overview of capabilities](http://linux.die.net/man/7/capabilities)

**Comment by buger** [comment]
Nice tip! Will add it to documentation.

**Comment by buger** [comment]
It took a while :)  Update README.
