### ISSUE TITLE
No redirects: flag provided but not defined

### ISSUE THREAD

**Issue by servomac** [buger/gor#153]
I'm unable to use the --output-http-redirects flag. This is the command used with its parameters

```
$ /usr/local/bin/gor --input-file borg_06-01_16\:38.gor --output-http "www.domain.es.test:81" --output-http-url-regexp "^*.domain.es" --output-http-redirects 10
Version: 0.9.2
flag provided but not defined: -output-http-redirects
[...]
```

Without the --output-http-redirects it works fine. Any idea?

**Comment by buger** [comment]
Well i think you should compile from source for now, this feature was not yet released under any number.

**Comment by servomac** [comment]
Thanks for your rapid response.
