### ISSUE TITLE
(curiosity) Record/playback of requests AND responses or just requests?

### ISSUE THREAD

**Issue by hangtwenty** [buger/gor#155]
It's clear that Gor allows you to record and playback requests, such as for testing load. From README, it looks like Gor does not handle the use-case of recording requests and responses. (Like [betamax](http://freeside.co/betamax/) or something.) Could Gor be extended for this use-case? Is something like this on the roadmap, or is it out of scope for Gor?

**Comment by eanderton** [comment]
I'd like to second this issue.  The Betamax For some of my work, it would be ideal if Gor could be used to test a program's ability to integrate with an external system (e.g. some REST-capable service).   I would like to record a live session, and then stand up Gor in a replay mode where my software can talk to it, and get those recorded responses (naturally for those requests that it already has recorded).

This way, one could easily use Gor to mock out external services in CI, in local development, or even in a closed environment.

**Comment by hangtwenty** [comment]
Right-o. From the README, I'm inclined to think Gor would allow one to do something betamax-ish but with this Proxy Server approach instead of the code-level, mocking approach.

**Comment by buger** [comment]
Yes, there plans of recording responses, and comparing them. I'm not sure about the way how report results of comparison. Just log file, or smth different...

**Comment by dPeS** [comment]
+1, report proposal: console output with line per mismatch with url, http codes expected, retrieved + some simple file format output, imo reporting, analyzing tool is different scope

**Comment by hangtwenty** [comment]
Comparison seems out of scope to me... Just echo back. Leave comparison to
another tool.

**Comment by dt** [comment]
I think what I'm proposing in #177 is slightly different, in that it would support comparing the responses of two arbitrary hosts, versus comparing to the original request's response. If #177 were implemented, it could potentially be used with one of the hosts configured to be the original host, so the end result would be similar to this (compare "original" response to something else), but I don't think it is exactly duplicative.

Also,  I think the approach of #177 could also be a tiny bit easier to implement, since we can get away with just firing off a second request in http_output, without having to refactor the input and output interfaces to pass a captured response around.

**Comment by buger** [comment]
@dt @hangtwenty @dPeS @eanderton Happy to announce working middleware draft: https://github.com/buger/gor/pull/162

Middleware accepts original and replayed responses, so now its possible to create middleware which compare responses. This is first major step, and i plan to include response comparison stats into Gor in next milestones.

Any testing and feedback invaluable. Read pull request PR for documentation and see examples and specs. Links to binaries included into PR description as well. Thanks!

**Comment by buger** [comment]
@dt @hangtwenty @dPeS @eanderton middleware released in  [0.10.0](https://github.com/buger/gor/releases/tag/0.10.0)

**Comment by salimane** [comment]
@buger  in the case whereby gor is used to record requests to a file using ``--output-file``, the response is not saved anywhere. So when you are replaying the requests from the file on another http endpoint, you have no access to the response headers to apply some custom logic depending on them.

Or is there a way to go about this ?

Basically, what I'm trying to do is modify the session token using the go middleware but in a 2 steps using the output-file option. And still replicate the login flow on the original requests.

Thanks

**Comment by buger** [comment]
@salimane well, actually with new release it should record responses by default, if its not, then probably it is bug, and i will check it.

**Comment by salimane** [comment]
@buger yep it does not record responses.
Thanks

**Comment by buger** [comment]
@salimane just to confirm, are we talking about input-raw? Because currently only raw input support response recording.

**Comment by salimane** [comment]
Oh I was using ``input-http`` because there was a guarantee of not loosing requests. ``input-raw`` does log responses.

**Comment by buger** [comment]
@salimane i have plans on supporting response handling in input-http in future releases, but it is not trivial.

**Comment by psisodia** [comment]
I have latest version of 16 for mac and I still don't see responses record for raw input. Not sure if I am using right version? Also I want to understand if I can verify I am actually creating traffic on server when replay from input file and output to http server, it does not write anything in console?

**Comment by buger** [comment]
@psisodia while replaying you can add `--stats --output-http-stats` command to see request count and latency stats. 

Regarding mac, do you have some weird network interfaces, or maybe using docker? I would suggest adding smth like `--input-raw-bpf-filter "port <port>"` to your command, to ignore IP checks. 

Thank you!
