### ISSUE TITLE
Properly reproducing requests with proxy

### ISSUE THREAD

**Issue by TrungACZNE** [buger/gor#156]
Hi

I have been trying out gor to test a squid proxy server I have running since it has some issues that randomly pop up. After capturing the squid traffic to a file and replaying it on another machine, I noticed that it doesn't work correctly.

Commands used:
```
$ gor --input-raw :3002 --output-file gor.replay
```
Replaying on another machine:
```
$ gor --input-file gor.replay --output-http :3002
```
(3002 is the default squid port)

I noticed that in Squid's access logs the requests come out as "GET /path/to/file" (request-URI has only path) but a quick peek into gor.replay shows that the requests are properly stored:
```
GET http://hostname.com/path/to/file
...
```
Since Squid is a proxy it expects request-URI to be the full qualified URI of the resource . This is stored correctly in the input, but the replay step missed out the hostname.

I think this is due to the http.ReadRequest call in output_http.go:35 , I think http package removes everything but the path from the request-URI (I'm sure it does for http.NewRequest()) 

Currently I handle this by modifying request.URL.Path after it has been formed when I turn on a flag
```			
request.URL.Path = request.URL.Scheme + "://" + request.Host + request.URL.Path
```

I'm not sure if this is an intended use case, so I'd like to hear what you think about this now/in the future.

**Comment by buger** [comment]
Well, usually domain specified in `Host:` header and url contains only path. 
What happens here is that most likely Go http client automatically strips domain from URL, and just adds Host header. Maybe its better to follow standards and check HOST header in Squid instead?

**Comment by buger** [comment]
Just to clarify, i'm talking about HTTP 1.1

Currently i'm working on sending original HTTP requests without any preprocessing, will keep you updated.

**Comment by buger** [comment]
@TrungACZNE  this should fix your issue https://github.com/buger/gor/pull/163 (already merged to master)

**Comment by TrungACZNE** [comment]
Thanks, much appreciated
