### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by Kooper** [buger/gor#166]
Hello,

When trying gor 0.9.6 I got several "slice bounds out of range" errors:

    panic: runtime error: slice bounds out of range
    
    goroutine 7737 [running]:
    runtime.panic(0x723780, 0x92b02f)
        /goroot/src/pkg/runtime/panic.c:279 +0xf5
    github.com/buger/gor/proto.Header(0xc20a50a000, 0x8bb3, 0x8bb3, 0xc20a7314b8, 0x4, 0x8, 0x0, 0x0, 0x0, 0x8ada, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:37 +0x1aa
    github.com/buger/gor/proto.SetHeader(0xc20a50a000, 0x8bb3, 0x8bb3, 0xc20a7314b8, 0x4, 0x8, 0xc20a436820, 0x11, 0x20, 0x0, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:49 +0x8b
    github.com/buger/gor/proto.SetHost(0xc20a50a000, 0x8bb3, 0x8bb3, 0xc20a436800, 0x18, 0x20, 0xc20a436820, 0x11, 0x20, 0x0, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:153 +0x3fe
    main.(*HTTPClient).Send(0xc208ba6bd0, 0xc20a50a000, 0x8bb3, 0x8bb3, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:101 +0x21e
    main.(*HTTPOutput).sendRequest(0xc20800eaa0, 0xc208ba6bd0, 0xc20a50a000, 0x8bb3, 0x8bb3)
        /gopath/src/github.com/buger/gor/output_http.go:146 +0x87
    main.(*HTTPOutput).Worker(0xc20800eaa0)
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x164
    created by main.(*HTTPOutput).WorkerMaster
        /gopath/src/github.com/buger/gor/output_http.go:77 +0x79

And another one:

    panic: runtime error: slice bounds out of range
    
    goroutine 45322 [running]:
    runtime.panic(0x723780, 0x92b02f)
        /goroot/src/pkg/runtime/panic.c:279 +0xf5
    github.com/buger/gor/proto.Path(0xc208046280, 0x79, 0x79, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/proto/proto.go:77 +0x117
    github.com/buger/gor/proto.SetHost(0xc208046280, 0x79, 0x79, 0xc2092b5420, 0x18, 0x20, 0xc2092b5440, 0x11, 0x20, 0x0, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:142 +0x75
    main.(*HTTPClient).Send(0xc208027c00, 0xc208046280, 0x79, 0x79, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:101 +0x21e
    main.(*HTTPOutput).sendRequest(0xc20800ea00, 0xc208027c00, 0xc208046280, 0x79, 0x79)
        /gopath/src/github.com/buger/gor/output_http.go:146 +0x87
    main.(*HTTPOutput).Worker(0xc20800ea00)
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x164
    created by main.(*HTTPOutput).WorkerMaster
        /gopath/src/github.com/buger/gor/output_http.go:77 +0x79

Unfortunately I can't figure out exact HTTP requests which caused it - debug mode in 0.9.6 doesn't print anything except [DEBUG] and Connecting/Disconnecting strings.

**Comment by Kooper** [comment]
One more trace:

    panic: runtime error: slice bounds out of range
    
    goroutine 4154852 [running]:
    runtime.panic(0x723780, 0x92b02f)
        /goroot/src/pkg/runtime/panic.c:279 +0xf5
    github.com/buger/gor/proto.Header(0xc2096c6000, 0x8ce3, 0x8ce3, 0xc208f969c0, 0x4, 0x8, 0x0, 0x0, 0x0, 0x699b, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:37 +0x1aa
    github.com/buger/gor/proto.SetHeader(0xc2096c6000, 0x8ce3, 0x8ce3, 0xc208f969c0, 0x4, 0x8, 0xc208ba7f20, 0x11, 0x20, 0x0, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:49 +0x8b
    github.com/buger/gor/proto.SetHost(0xc2096c6000, 0x8ce3, 0x8ce3, 0xc208ba7f00, 0x18, 0x20, 0xc208ba7f20, 0x11, 0x20, 0x0, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:153 +0x3fe
    main.(*HTTPClient).Send(0xc209067a40, 0xc2096c6000, 0x8ce3, 0x8ce3, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:101 +0x21e
    main.(*HTTPOutput).sendRequest(0xc2080189b0, 0xc209067a40, 0xc2096c6000, 0x8ce3, 0x8ce3)
        /gopath/src/github.com/buger/gor/output_http.go:146 +0x87
    main.(*HTTPOutput).Worker(0xc2080189b0)
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x164
    created by main.(*HTTPOutput).WorkerMaster
        /gopath/src/github.com/buger/gor/output_http.go:77 +0x79

**Comment by buger** [comment]
Thanks for the report, I think i found it! 

When Gor just started it may receive only part of TCPMessage, and since --input-raw did not do any verification, it may try to send uncompleted request. 

For now i made it more stable to such errors, long term plan is to add message verification. 
I just release https://github.com/buger/gor/releases/tag/0.9.7 version, pls check it.

**Comment by Kooper** [comment]
I gladly confirm that the problem is fixed in gor 0.9.7
Thank you very much
