### ISSUE TITLE
Host rewriting doesn't seem to work.

### ISSUE THREAD

**Issue by hyvs** [buger/gor#174]
Hi, 

since version 0.9.5 host rewriting is not working anymore :

In version 0.9.7 :

gor --input-raw :80 --output-http http://staging-host --http-set-header "Host: www.example.com"

> tcpdump -lAi eth0 -n src host 176.xx.xx.xx -vvvs 1024
```
GET / HTTP/1.1
Host: staging-host:80
...
```

In version 0.9.4 : 

gor --input-raw :80 --output-http http://staging-host --output-http-header "Host: www.example.com"

> tcpdump -lAi eth0 -n src host 176.xx.xx.xx -vvvs 1024
```
GET / HTTP/1.1
Host: www.example.com
...
```

I suspect [http_client.go:118](https://github.com/buger/gor/blob/ac3e20978717b49b90bbd724d06711ab4d692fd4/http_client.go#L118) to overwrite Host, previously set by [http_modifier.go:52](https://github.com/buger/gor/blob/ac3e20978717b49b90bbd724d06711ab4d692fd4/http_modifier.go#L52)

Related issues: [#74](https://github.com/buger/gor/issues/74)

Thanks.

**Comment by buger** [comment]
I see the problem, thank you for pointing!

Just curious what is the use case of using different Host header domain ('www.example.com`) then specified in output-http (`staging-host`)?

**Comment by hyvs** [comment]
The use case is a website migration. Our old and new servers handle our www.example.com host.

We want to avoid any DNS modification before final migration. It's easier to replay our production traffic to the new load balancer (http://staging-host). Then, we compare HTTP status and responses times to detect any possible issues.

**Comment by buger** [comment]
@hyvs fixed in master

**Comment by buger** [comment]
@webhav 1.3 was recently released, can you try it out?
