### ISSUE TITLE
Link to "Running Gor, the HTTP traffic replayer, as a service on AWS Elastic Beanstalk"

### ISSUE THREAD

**Issue by jakubholynet** [buger/gor#179]
Hello,

I have written about [running Gor as a service on AWS Elastic Beanstalk](https://theholyjava.wordpress.com/2015/07/30/run-gor-the-http-traffic-replayer-as-a-service-on-aws-elastic-beanstalk/). It is interesting both for those who might want to run Gor as a daemon on whatever Linux, and for those that actually use AWS.

It would perhaps be worth linking to it from the README as running Gor as a service is something many people might want.

Thanks!

**Comment by buger** [comment]
Thanks! I will definitely share this article and will implement daemon support :)
