### ISSUE TITLE
Request error: read tcp: i/o timeout

### ISSUE THREAD

**Issue by chriseldredge** [buger/gor#181]
Not sure if this is a problem in gor or somewhere else. I'm duplicating traffic from a production server to a new (otherwise) idle server to load test it before replacement.

Within about 10 seconds, I start seeing i/o timeout.

I suspect the new server is taking more than 10 seconds before beginning to write the response. I didn't see anything in the docs or settings about such an idle timeout.

```
sudo ./gor --input-raw :80 --output-http '10.0.0.1:80' --output-http-stats=true --stats=true
Version: 0.9.7
2015/07/30 19:00:04 output_http:latest,mean,max,count,count/second
2015/07/30 19:00:04 output_http:0,0,0,0,0
2015/07/30 19:00:09 output_http:1,2,4,21,4
2015/07/30 19:00:12 Request error: read tcp 10.0.0.1:80: i/o timeout
2015/07/30 19:00:13 Request error: read tcp 10.0.0.1:80: i/o timeout
2015/07/30 19:00:13 Request error: read tcp 10.0.0.1:80: i/o timeout
2015/07/30 19:00:14 output_http:6,5,6,23,4
2015/07/30 19:00:14 Request error: read tcp 10.0.0.1:80: i/o timeout
2015/07/30 19:00:16 Request error: read tcp 10.0.0.1:80: i/o timeout
2015/07/30 19:00:17 Request error: read tcp 10.0.0.1:80: i/o timeout
```

**Comment by buger** [comment]
I guess you talking about some sort of warmup time? If so, i'm not sure how to handle it properly, probably it is not Gor duty. 

But i just added support for configurable http timeouts https://github.com/buger/gor/pull/183

**Comment by chriseldredge** [comment]
That new option appears to be what I was running into. I'm load testing a server that may take more than 5 seconds to respond and this new switch will allow me to increase gor's timeout.
