### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by pauloborges** [buger/gor#187]
Using `x64 0.9.7` binary from https://github.com/buger/gor/releases.

I'm aware of #82, but the stacktrace is different:

	$ sudo gor/gor --input-raw :8080 --output-http "http://staging.XXXXXXXXXX|1%" --verbose
	Version: 0.9.7
	2015/08/05 15:49:19 Received packet with same sequence
	2015/08/05 15:49:19 Received packet with same sequence
	2015/08/05 15:49:19 Received packet with same sequence
	2015/08/05 15:49:20 Received packet with same sequence
	2015/08/05 15:49:20 Received packet with same sequence
	2015/08/05 15:49:20 Received packet with same sequence
	[DEBUG] 2015/08/05 15:49:20 [HTTPClient] Connecting: http://staging.XXXXXXXXXX:80
	2015/08/05 15:49:20 Received packet with same sequence
	2015/08/05 15:49:20 Received packet with same sequence
	panic: runtime error: index out of range

	goroutine 24 [running]:
	runtime.panic(0x723780, 0x92b01c)
		/goroot/src/pkg/runtime/panic.c:279 +0xf5
	github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc208018a50)
		/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:62 +0x14e
	created by github.com/buger/gor/raw_socket_listener.NewListener
		/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:50 +0x165

	goroutine 16 [select]:
	main.Start(0x0)
		/gopath/src/github.com/buger/gor/emitter.go:14 +0x193
	main.main()
		/gopath/src/github.com/buger/gor/gor.go:48 +0x1ba

	goroutine 19 [finalizer wait]:
	runtime.park(0x423e10, 0x92f078, 0x92d2c9)
		/goroot/src/pkg/runtime/proc.c:1369 +0x89
	runtime.parkunlock(0x92f078, 0x92d2c9)
		/goroot/src/pkg/runtime/proc.c:1385 +0x3b
	runfinq()
		/goroot/src/pkg/runtime/mgc0.c:2644 +0xcf
	runtime.goexit()
		/goroot/src/pkg/runtime/proc.c:1445

	goroutine 20 [runnable]:
	main.(*RAWInput).listen(0xc20803d060, 0x7fff4762993c, 0x5)
		/gopath/src/github.com/buger/gor/input_raw.go:45 +0x235
	created by main.NewRAWInput
		/gopath/src/github.com/buger/gor/input_raw.go:20 +0x80

	goroutine 21 [chan receive]:
	main.(*HTTPOutput).WorkerMaster(0xc2080189b0)
		/gopath/src/github.com/buger/gor/output_http.go:75 +0x47
	created by main.NewHTTPOutput
		/gopath/src/github.com/buger/gor/output_http.go:68 +0x17f

	goroutine 22 [chan receive]:
	main.(*RAWInput).Read(0xc20803d060, 0xc2080b0000, 0x500000, 0x500000, 0x0, 0x0, 0x0)
		/gopath/src/github.com/buger/gor/input_raw.go:26 +0x7b
	main.CopyMulty(0x7fc341d7afd0, 0xc20803d060, 0xc208034c30, 0x1, 0x1, 0x0, 0x0)
		/gopath/src/github.com/buger/gor/emitter.go:29 +0xf4
	created by main.Start
		/gopath/src/github.com/buger/gor/emitter.go:10 +0xd5

	goroutine 25 [runnable]:
	net.runtime_pollWait(0x7fc341d7c1e8, 0x72, 0x0)
		/tmp/makerelease703080346/go/src/pkg/runtime/netpoll.goc:146 +0x66
	net.(*pollDesc).Wait(0xc208024060, 0x72, 0x0, 0x0)
		/goroot/src/pkg/net/fd_poll_runtime.go:84 +0x46
	net.(*pollDesc).WaitRead(0xc208024060, 0x0, 0x0)
		/goroot/src/pkg/net/fd_poll_runtime.go:89 +0x42
	net.(*netFD).readFrom(0xc208024000, 0xc2085c4000, 0xa000, 0xa000, 0x0, 0x0, 0x0, 0x7fc341d7a3f0, 0xb)
		/goroot/src/pkg/net/fd_unix.go:269 +0x3db
	net.(*IPConn).ReadFromIP(0xc208040020, 0xc2085c4000, 0xa000, 0xa000, 0x14, 0xc208856b70, 0x0, 0x0)
		/goroot/src/pkg/net/iprawsock_posix.go:82 +0x132
	net.(*IPConn).ReadFrom(0xc208040020, 0xc2085c4000, 0xa000, 0xa000, 0x14, 0x0, 0x0, 0x0, 0x0)
		/goroot/src/pkg/net/iprawsock_posix.go:102 +0x142
	github.com/buger/gor/raw_socket_listener.(*Listener).readRAWSocket(0xc208018a50)
		/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:85 +0x1cb
	created by github.com/buger/gor/raw_socket_listener.NewListener
		/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:51 +0x17d

    [...] // The stacktrace is huge.

The whole stacktrace can be found here: https://gist.github.com/pauloborges/5b2683afb04fd72fa6f9

**Comment by buger** [comment]
What is the approx. requests (or bytes) per second?

**Comment by buger** [comment]
Should be fixed in [v0.9.8](https://github.com/buger/gor/releases/tag/0.9.8) release.

**Comment by pauloborges** [comment]
Sorry for the delay, the approximate number of requests is 20k. I'll try again with the new version. Thank you!

**Comment by pauloborges** [comment]
It worked!
