### ISSUE TITLE
Getting 301 redirects from nginx

### ISSUE THREAD

**Issue by tcmb** [buger/gor#189]
Hi, we're trying to use `gor` for load testing a new server and find the possibility of throttling playback very appealing!

Currently we're doing very simple first steps and are running into an issue where we're getting 301 responses for replayed requests, where the original requests were getting 200 responses.

We've tried with `input-raw` and with `input-http` and the results are the same. The original requests are issued from `curl` as a client.

These are the commands we're using for recording and replaying (gor 0.9.8):

`./gor -debug -verbose --input-http :28020 --output-file requests.log`

`./gor -debug -verbose --input-file requests.log --output-http ourserver.example.com`

We have gor as an upstream in our nginx config, I can post the relevant entries here if needed, but as I said we were getting the same results with `input-raw`.

The request is issued from curl as `curl http://ourserver.example.com/version`.

This is an entry from `/var/log/nginx/access.log` for an original request:

`78.xx.xxx.xx - - [06/Aug/2015:16:22:11 +0200] "GET /version HTTP/1.1" 200 594 "-" "curl/7.38.0"`

And this is an entry from `/var/log/nginx/access.log` for a replayed request:

`78.xx.xxx.xx - - [06/Aug/2015:16:25:36 +0200] "GET /version HTTP/1.0" 301 193 "-" "curl/7.38.0"`

It's weird that the replayed request uses 'HTTP/1.0', and in addition we're seeing a 'Connection: close' header inserted in the replayed request, which is not there in the original one. But we're not sure if the different response is actually caused by those differences.

Any hints for further debugging or towards what we might be doing wrong are much appreciated!

**Comment by tcmb** [comment]
We found the cause, there was a `rewrite` rule that returned 301s, presumably because the replayed requests included the port number (`ourserver.example.com:80`). This is a bit confusing, because the debug output from replaying suggests that the `Host:` header would not contain the port:

```
[DEBUG][PID 109741] 2015/08/07 10:30:11 [HTTPClient] Connecting: http://ourserver.example.com:80
[DEBUG][PID 109741] 2015/08/07 10:30:11 [HTTPClient] Received: 790
[DEBUG][PID 109713] 2015/08/07 10:30:14 [EMITTER] Sending payload, size: 110 First 500 bytes: GET /version HTTP/1.0
Host: ourserver.example.com
Accept: */*
Connection: close
User-Agent: curl/7.38.0
```

**Comment by buger** [comment]
Yeah, as you can see this debug output comes from EMITTER before it get processed by HTTP output, so it not yet modified (rewrite host). 

Question here is why you get redirects when you have port in Host header. RFC says it is totally OK, but if it cause issues i can remove port for 443 and 80.

**Comment by buger** [comment]
This should fix your issue and contains links to pre-compiled binaries: https://github.com/buger/gor/pull/190
