### ISSUE TITLE
steadily increasing memory use

### ISSUE THREAD

**Issue by chunacatsunflower** [buger/gor#193]
Hi,

first, let me say that Gor is a very useful tool, and I'll be glad to give a hand troubleshooting and debugging this issue.  We are looking at Gor to duplicate traffic from our production tomcat server to a test instance, but it steadily uses more and more memory until it crashes.  I downloaded 0.10.0 yesterday, and I am invoking Gor with the following command:

$ sudo ./gor --input-raw :8080 --output-http "http://aws.ip.reda.cted:8080/"

Our system receives a significant volume of heartbeats (1-2 per second) from devices around the world, as well as irregular data payloads (fairly small, generally < 500 bytes).  With this load, Gor is using an additional 1M of memory every minute or so ( running for 30 minutes), and increasing faster and faster.

Have you seen this type of behavior previously, or barring that, do you have any suggestions on where I should start looking in the code?  I'm not to familiar with GO, but I'm always interested in adding new languages to my repertoire.

**Comment by buger** [comment]
@chunacatsunflower thanks, looks like we have a leak, definitely will check it!

**Comment by chunacatsunflower** [comment]
I have been seeing a few errors in the output, I'm not sure if it's related:

2015/08/25 14:11:43 Request error: write tcp 54.90.10.141:8080: connection reset by peer
2015/08/25 14:11:45 Request error: write tcp 54.90.10.141:8080: broken pipe
2015/08/25 14:11:46 Request error: write tcp 54.90.10.141:8080: broken pipe
2015/08/25 14:11:47 Request error: write tcp 54.90.10.141:8080: broken pipe
2015/08/25 14:11:48 Request error: write tcp 54.90.10.141:8080: broken pipe
2015/08/25 14:11:53 Received packet with same sequence
2015/08/25 14:11:58 Received packet with same sequence
2015/08/25 14:12:00 Received packet with same sequence
2015/08/25 14:12:12 PANIC: pkg: send on closed channel /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:185 (0x59535e)
/goroot/src/runtime/asm_amd64.s:401 (0x453dc5)
/goroot/src/runtime/panic.go:387 (0x42b4a8)
/goroot/src/runtime/chan.go:131 (0x41a613)
/goroot/src/runtime/chan.go:68 (0x41a463)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:248 (0x5928fe)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:113 (0x59189a)
/goroot/src/runtime/asm_amd64.s:2232 (0x455ee1)

**Comment by chunacatsunflower** [comment]
I just realized that I left of a potentially useful piece of info - we are filtering the forwarded http requests using --http-allow-url;  We have an admin gui that we do not care about forwarding, with some javascript that calls a rest service every second.

**Comment by buger** [comment]
@chunacatsunflower issue should be fixed, check this PR https://github.com/buger/gor/pull/194 (binaries included). I still need to fix tests, but it should work.

**Comment by buger** [comment]
https://github.com/buger/gor/pull/194 is merged, you can still use binaries included into PR. Once i'll release new version with fixes, i will notify.
