### ISSUE TITLE
Gor replay server terminates after few hours of execution

### ISSUE THREAD

**Issue by pmittal1982** [buger/gor#196]
I am using Gor for replicating my production nginx load to the new architecture we have build using python stack. The server starts ok, but after few hours sometimes I start getting the following error:

panic: runtime error: slice bounds out of range

goroutine 2354 [running]:
runtime.panic(0x6940e0, 0x9e04ea)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/buger/gor/proto.IsHTTPPayload(0xc210e9626f, 0x2, 0x2, 0xc210e9626f)
	/home/ubuntu/Go/src/github.com/buger/gor/proto/proto.go:217 +0x10f
main.(*HTTPOutput).sendRequest(0xc21001f410, 0xc211412310, 0xc210e96230, 0x41, 0x41)
	/home/ubuntu/Go/src/github.com/buger/gor/output_http.go:191 +0xf4
main.(*HTTPOutput).startWorker(0xc21001f410)
	/home/ubuntu/Go/src/github.com/buger/gor/output_http.go:126 +0x143
created by main.(*HTTPOutput).workerMaster
	/home/ubuntu/Go/src/github.com/buger/gor/output_http.go:101 +0x65

goroutine 1 [select]:
main.Start(0x0)
	/home/ubuntu/Go/src/github.com/buger/gor/emitter.go:33 +0x23c
main.main()
	/home/ubuntu/Go/src/github.com/buger/gor/gor.go:52 +0x1cc

So my requirement is to keep replicating the traffic continuously for couple of days. Please suggest if you need any other details.

**Comment by justanshulsharma** [comment]
@pmittal1982 have you done changes in sysctl.?

**Comment by pmittal1982** [comment]
No, can you please let me know what exactly I need to do?

**Comment by justanshulsharma** [comment]
@pmittal1982 first please try to use binaries mention in this
https://github.com/buger/gor/pull/194

**Comment by pmittal1982** [comment]
So can these binaries be executed on ubuntu, last time I tried downloading the binary it was not running and therefore I checked out the code and built it.

**Comment by justanshulsharma** [comment]
If you are directly replaying traffic from production to xyz server in that case you only need this on production and if you are storing requests and replaying from another server in that case you need it on both servers.

**Comment by pmittal1982** [comment]
Sure, I tried running these binaries. It throws:

        TECH-PIYUSH:Downloads pmittal$ ./gor 
        -bash: ./gor: cannot execute binary file
        TECH-PIYUSH:Downloads pmittal$ 

Am I missing anything. I am actually new to goLang, using it first time.

**Comment by justanshulsharma** [comment]
output of uname -a ?

**Comment by justanshulsharma** [comment]
You can use https://github.com/buger/gor/tree/fix-memory-leaks this branch to build in that case, there is an issue with gor of memory leak. BTW to achieve the top most performance you should tune the source server system limits:

net.ipv4.tcp_max_tw_buckets = 65536
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 0
net.ipv4.tcp_max_syn_backlog = 131072
net.ipv4.tcp_syn_retries = 3
net.ipv4.tcp_synack_retries = 3
net.ipv4.tcp_retries1 = 3
net.ipv4.tcp_retries2 = 8
net.ipv4.tcp_rmem = 16384 174760 349520
net.ipv4.tcp_wmem = 16384 131072 262144
net.ipv4.tcp_mem = 262144 524288 1048576
net.ipv4.tcp_max_orphans = 65536
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_syncookies = 0

**Comment by pmittal1982** [comment]
Replay server:

        ubuntu@ip-172-31-23-60:~$ uname -a
Linux ip-172-31-23-60 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-23-60:~$ 

Storing servers:

        Linux ip-10-0-0-98.ap-southeast-1.compute.internal 2.6.32-358.14.1.el6.x86_64 #1 SMP Mon Jun 17 15:54:20 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux

        Linux ip-10-0-0-52.ap-southeast-1.compute.internal 2.6.32-358.14.1.el6.x86_64 #1 SMP Mon Jun 17 15:54:20 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by buger** [comment]
Pls try #194 once more time, binaries are updated.

**Comment by buger** [comment]
Also this exact error mentioned in issue description was fixed in 0.10 release (but better use #194 until i release new version). It happens because sometimes it does not receive all the packets from the http message, which results in corrupted payload.

**Comment by buger** [comment]
Should be fixed in [v0.10.1](https://github.com/buger/gor/releases/tag/v0.10.1)
