### ISSUE TITLE
CLI options typo

### ISSUE THREAD

**Issue by pmittal1982** [buger/gor#197]
The "--http-disallow-url" CLI option has been misspelled as "--http-diallow-url". i.e character "s" missing in disallow. Kindly fix it.

Also it would be really helpful if you can suggest me how to disallow the URLs coming from a specific domain. I am replicating the nginx server traffic, but that nginx is configured for various domains e.g api.xxx.com, admin.xxx.com etc. But I want to allow only "api.xxx.com" traffic to replicate.

**Comment by justanshulsharma** [comment]
@pmittal1982 sent PR for typo issue https://github.com/buger/gor/pull/198
hope it will be fixed in next release.

**Comment by pmittal1982** [comment]
Thanks a lot.

**Comment by justanshulsharma** [comment]
cheers :beers:

**Comment by pmittal1982** [comment]
Any recommendation for the second question:

"Also it would be really helpful if you can suggest me how to disallow the URLs coming from a specific domain. I am replicating the nginx server traffic, but that nginx is configured for various domains e.g api.xxx.com, admin.xxx.com etc. But I want to allow only "api.xxx.com" traffic to replicate."

**Comment by justanshulsharma** [comment]
ping @buger

**Comment by buger** [comment]
Give me some time to woke up :D

**Comment by justanshulsharma** [comment]
haha :+1:

**Comment by buger** [comment]
@pmittal1982 

> "Also it would be really helpful if you can suggest me how to disallow the URLs coming from a specific domain. I am replicating the nginx server traffic, but that nginx is configured for various domains e.g api.xxx.com, admin.xxx.com etc. But I want to allow only "api.xxx.com" traffic to replicate."

If we talking about HTTP1.1, which is usually by default, host should be in http HOST header, so you can try smth like: --http-allow-header "Host: api.xxx.com"
