### ISSUE TITLE
How to force ordering of requests from input-file

### ISSUE THREAD

**Issue by salimane** [buger/gor#199]
Currently I'm using gor to replay requests using ``--input-file`` option. The requests get replayed in the wrong order. 
Is there a workaround to force the order that gor replay the requests especially if there are from file ?
Thanks

**Comment by buger** [comment]
Can you manually check this file (it is human readable format), and check request timestamps (included as last value at payload header). We need to find out if request timestamps in wrong order, or actual requests.

**Comment by buger** [comment]
If inside file you will find the case when you see requests in wrong order, for debugging reasons you can just paste both requests here (just remove all sensitive information).

**Comment by salimane** [comment]
It was actual requests even though the file has the right order. I'll try to reproduce it and update here
Thanks

**Comment by buger** [comment]
@salimane any updates?

**Comment by salimane** [comment]
@buger I'm very sorry , I parked this for a moment due to other tasks, but I will definitely get back to this because, well, I need it :)
Thanks

**Comment by salimane** [comment]
@buger I've tried unsuccessfully to reproduce with v1.10.1 . So thanks very much. I'll close this.
