### ISSUE TITLE
Gor --input-http still sometimes send corrupted body payload

### ISSUE THREAD

**Issue by salimane** [buger/gor#200]
In the readme, we have :
``Due to the fact that Gor can't guarantee interception of all packets, for large payloads > 200kb there is chance of missing some packets and corrupting body. Treat it as a feature and chance to test broken bodies handling :) The only way to guarantee delivery is using --input-http, but you will miss some features.``

But I'm still get truncated POST body. How to work around this ?

Thanks

**Comment by buger** [comment]
You still get truncated bodies even using input-http ?

**Comment by salimane** [comment]
yep when using ``input-http``, the body got truncated.
Thanks

**Comment by buger** [comment]
I see, what is the expected body length? Note that current buffer is 5mb, but i can make it configurable if needed.

**Comment by salimane** [comment]
hmm... I don't think the body length I was sending was more than 5mb. It was way less than that. But the body payload send to the receiving server was just truncated somehow.
Thanks

**Comment by buger** [comment]
Thanks, i will continue with the tests

**Comment by buger** [comment]
I added unit test https://github.com/buger/gor/commit/60ddd535bc57342d8fde7bd40cb8b8d32e71eaf5 and it seeps to be passing. How did you checked that body is truncated? You got issues on replay side? Which output plugin did you used?

**Comment by salimane** [comment]
It was happening randomly. I was using ``input-http`` and ``output-http``. I'll try to reproduce it
Thanks

**Comment by salimane** [comment]
@buger I've tried unsuccessfully to reproduce with v1.10.1 . So thanks very much. I'll close this.

**Comment by pratikdotexe** [comment]
2024 And this issue still haunting us.
