### ISSUE TITLE
Only http or some other tcp supported?

### ISSUE THREAD

**Issue by Fullmetal8ender** [buger/gor#205]
Hi. You write a very useful progam. But does it support only http? I have some binary protocol that is not encrypted. Can I use gor for duplicate this traffic?

**Comment by buger** [comment]
I'm working on supporting binary based protocols like thrift, do not have ETA yet, but this is quite big priority.

**Comment by Fullmetal8ender** [comment]
Good! Thrift is what I need.

**Comment by MartyRong** [comment]
Support thrift now?

**Comment by buger** [comment]
Support for thrift considered as Gor Pro option https://gortool.com, thank you!

**Comment by buger** [comment]
@MartyRong @Fullmetal8ender happy to announce that Thrift is supported in just released  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) version.
