### ISSUE TITLE
Problem installing Gor from source

### ISSUE THREAD

**Issue by EmanSalah** [buger/gor#218]
Dear Buger,
 I tried installing Gor either using go get github.com/buger/gor or from a manually downloaded Zip file,
but when I run go build gor.go it gives:

# command-line-arguments
./gor.go:35: undefined: VERSION
./gor.go:38: undefined: InitPlugins
./gor.go:40: undefined: Plugins in Plugins.Inputs
./gor.go:40: undefined: Plugins in Plugins.Outputs
./gor.go:52: undefined: Start

and if I ran just go build as you suggested (I run it from $GOPATH/src/github.com/buger/gor director) I get:

elasticsearch.go:5:2: cannot find package "github.com/buger/elastigo/api" in any of:
	/opt/go/src/github.com/buger/elastigo/api (from $GOROOT)
	/home/eman/src/github.com/buger/elastigo/api (from $GOPATH)
elasticsearch.go:6:2: cannot find package "github.com/buger/elastigo/core" in any of:
	/opt/go/src/github.com/buger/elastigo/core (from $GOROOT)
	/home/eman/src/github.com/buger/elastigo/core (from $GOPATH)
elasticsearch.go:7:2: cannot find package "github.com/buger/gor/proto" in any of:
	/opt/go/src/github.com/buger/gor/proto (from $GOROOT)
	/home/eman/src/github.com/buger/gor/proto (from $GOPATH)
input_raw.go:4:2: cannot find package "github.com/buger/gor/raw_socket_listener" in any of:
	/opt/go/src/github.com/buger/gor/raw_socket_listener (from $GOROOT)
	/home/eman/src/github.com/buger/gor/raw_socket_listener (from $GOPATH)

Here are my Environment Settings: 
go version go1.5 linux/amd64
GOARCH="amd64"
GOBIN="/home/eman/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/eman"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Your help is highly appreciated 

Thanks a lot

**Comment by buger** [comment]
Did you tried binaries https://github.com/buger/gor/releases?

**Comment by EmanSalah** [comment]
So sorry for late reply, and thanks for your hint, using the latest release binaries solved my problem.

Thanks a lot

**Comment by JiLongQiu** [comment]
https://github.com/buger/gor/releases

can you tell me how can i install the binary file ?

i download the gor_0.10.1_x64.tar.gz, and i get a file named 'gor' after unzip the gz file

how can i use the 'gor' file ?
