### ISSUE TITLE
MacOS support 

### ISSUE THREAD

**Issue by buger** [buger/gor#22]
Right now its not supported because *BSD system and not allow TCP/UDP traffic capture using RAW sockets. Need to use libpcap for *BSD systems. 

Check #21 and #8 for more details.

**Comment by salimane** [comment]
any update on this ?
Thanks

**Comment by buger** [comment]
I'm not sure about release date, but i'm (or someone else) going to implement it using https://github.com/google/gopacket

**Comment by Blender3D** [comment]
Does Gor at least support replaying traffic on OS X?

**Comment by buger** [comment]
Yes, totally, I plan to include binaries for Mac for next release

On Monday, September 7, 2015, Blender3D <notifications@github.com> wrote:

> Does Gor at least support replaying traffic on OS X?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/22#issuecomment-138125080>.
>


-- 
Sincerely yours Leonid Bugaev
leonsbox@gmail.com
http:// <http://buger.github.com>leonsbox.com

**Comment by buger** [comment]
Released https://github.com/buger/gor/releases/tag/v0.11.0 which use libpcap engine for intercepting traffic. Lipcap fully supports mac os.
