### ISSUE TITLE
"Worker failed on write, exitings and starting new worker"

### ISSUE THREAD

**Issue by left2right** [buger/gor#220]
when i use gor , i meet this , i want to know what cause this happened, thx

**Comment by JiLongQiu** [comment]
I meet the problem too

**Comment by dny238** [comment]
i got the error when I ran it like this:
./gor --input-raw :80 --output-tcp www2.mydomain.com:80

but not when I ran it like this
./gor --input-raw :80 --output-http "http://www2.mydomain.com"

I both my production and test sites are on the same box in my 'test' but have different host headers. 
Hope this helps somewhat.
Rob

**Comment by buger** [comment]
I added more debugging to the latest master. Expect release within this week.
