### ISSUE TITLE
Limiting based on response body?

### ISSUE THREAD

**Issue by Sazpaimon** [buger/gor#221]
I have a situation where I want to only send a certain percentage of session tokens to my non-prod environment. This works fine for already established sessions, as the session ID is part of the request and I can use` --http-param-limiter`, however I can't see a way to do something like this using the middleware layer. According to the documentation, it appears that filtering can only be done at the request layer and not at the response layer. Is something like this possible?

**Comment by salimane** [comment]
@Sazpaimon, currently there is no filtering on the request layer, unless you write custom middleware to handle your specific use case.
Thanks

**Comment by buger** [comment]
Worth noticing that response filtering may be considered as future option,
for now you can filter requests by their responses using middleware.

On Sunday, 24 April 2016, Salimane Adjao Moustapha <notifications@github.com>
wrote:

> @Sazpaimon <https://github.com/Sazpaimon>, currently there is no
> filtering on the request layer, unless you write custom middleware to
> handle your specific use case.
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/221#issuecomment-213900212>
>


-- 
Sincerely yours Leonid Bugaev
leonsbox@gmail.com
http:// <http://buger.github.com>leonsbox.com
