### ISSUE TITLE
Gzip request body corrupted

### ISSUE THREAD

**Issue by SaurabhJha** [buger/gor#224]
I think Gor is not able to deal with Gzipped requests. I am trying to unzip it using the following python code
            d = zlib.decompressobj(16+zlib.MAX_WBITS)
            body = d.decompress(request.body)

and it gives the error
error: Error -3 while decompressing data: incorrect header check

Can this stuff be handled? Thanks

**Comment by buger** [comment]
Sorry for such delay! There were lot of changes, try the latest release https://github.com/buger/gor/releases/tag/v0.12.0
