### ISSUE TITLE
POST replay takes a long time

### ISSUE THREAD

**Issue by hankl** [buger/gor#226]
Hello @buger,

Thanks for writing gor.  I've started to paly with it. It works great. 

But I noticed a strange behavior when replaying POST request, it takes a long time about 5s. GET request is very fast. 

Is there some option to set?

Thanks. 

PS: This strange behavior appears when sending POST request by Chrome plugin :postman. Other plugin such as Poster  seems OK.

**Comment by nikhilp-flipkart** [comment]
None of my POST requests are being replayed. The body is in JSON format.

**Comment by justanshulsharma** [comment]
@nikhilp-flipkart can you please post here more details about your request.

**Comment by buger** [comment]
@nikhilp-flipkart <https://github.com/nikhilp-flipkart> you can run Gor in
debug mode to see detailed HTTP level requests.

On Tue, Dec 8, 2015 at 12:26 PM, Anshul Sharma <notifications@github.com>
wrote:

> @nikhilp-flipkart <https://github.com/nikhilp-flipkart> can you please
> post here more details about your request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/226#issuecomment-162855310>.
>



-- 
Sincerely yours Leonid Bugaev
leonsbox@gmail.com
http:// <http://buger.github.com>leonsbox.com

**Comment by buger** [comment]
@hankl any chance you can add more debugging information here? 
For example full HTTP payload for `Postman` and for `Poster` to see the difference: --output-dummy should do the work, or --verbose --debug.

**Comment by buger** [comment]
Just release new version https://github.com/buger/gor/releases/tag/v0.12.0 pls check it.
