### ISSUE TITLE
Does GOR do response suppression ? 

### ISSUE THREAD

**Issue by AdityaS05** [buger/gor#228]
Hi,

GOR can be used to duplicate requests but each of the servers that the request is sent to - will also respond back.

Does GOR do duplicate response suppression.

Thanks,
Aditya Shantanu

**Comment by buger** [comment]
If you run it in duplication mode, middleware should receive 2 copies. But you can use --split-output option and instead of duplicating do round robin. Wha is your final goal?

**Comment by AdityaS05** [comment]
The end goal is to use GOR as the forwarding agent in an actively replicated architecture. So basically I want to client to send one request and havebir processed on two servers independently (so that even if one of them dies, the other continues to serve the request). But because of this I would get back two responses and I want to supress one of these two

**Comment by buger** [comment]
I do not think that Gor will be good for this task because currently it does not guarantee consistency, which you trying to achieve. 
But even so, you probably can write middleware for that, both response requests should have same ID.
