### ISSUE TITLE
Crashed when replaying : panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by hankl** [buger/gor#231]
[root@agent237 liuliang]# ./gor --input-file  "account-2G-token.gor|500%" --output-http "https://**.**.com"   --middleware   "./middleware.jar"
Version: 0.10.1

panic: runtime error: slice bounds out of range

goroutine 5 [running]:
main.payloadMeta(0xc20800fd89, 0x9c, 0x277, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/protocol.go:70 +0x120
main.(*FileInput).emit(0xc20803aba0)
        /gopath/src/github.com/buger/gor/input_file.go:62 +0x222
created by main.NewFileInput
        /gopath/src/github.com/buger/gor/input_file.go:27 +0xe5

goroutine 1 [select]:
main.Start(0x0)
        /gopath/src/github.com/buger/gor/emitter.go:33 +0x339
main.main()
        /gopath/src/github.com/buger/gor/gor.go:52 +0x200

goroutine 17 [chan receive, 1 minutes]:
main.(*HTTPOutput).workerMaster(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:98 +0x4b
created by main.NewHTTPOutput
        /gopath/src/github.com/buger/gor/output_http.go:91 +0x2ad

goroutine 33 [select]:
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 34 [select]:
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 35 [IO wait]:
net.(*pollDesc).Wait(0xc20b1c79c0, 0x72, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20b1c79c0, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20b1c7960, 0xc20b1ddc00, 0x400, 0x400, 0x0, 0x7f28d4a3fbb0, 0xc20b228cc0)
        /goroot/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20c9c01c8, 0xc20b1ddc00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /goroot/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20b1eb320, 0x7f28d4a45bf8, 0xc20c9c01c8, 0x5, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20b232840, 0x16, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).readHandshake(0xc20b232840, 0x0, 0x0, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:779 +0xe7
crypto/tls.(*Conn).clientHandshake(0xc20b232840, 0x0, 0x0)
        /goroot/src/crypto/tls/handshake_client.go:141 +0x110a
crypto/tls.(*Conn).Handshake(0xc20b232840, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:977 +0xf1
main.(*HTTPClient).Connect(0xc20800a380, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:81 +0x2d2
main.(*HTTPClient).Send(0xc20800a380, 0xc20b23203f, 0x246, 0x246, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:126 +0x1101
main.(*HTTPOutput).sendRequest(0xc20804c190, 0xc20800a380, 0xc20b232000, 0x285, 0x285)
        /gopath/src/github.com/buger/gor/output_http.go:195 +0x180
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:125 +0x1b9
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 36 [IO wait]:
net.(*pollDesc).Wait(0xc20b1c7950, 0x72, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20b1c7950, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20b1c78f0, 0xc20b1dd400, 0x400, 0x400, 0x0, 0x7f28d4a3fbb0, 0xc20b228ca8)
        /goroot/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20c9c01c0, 0xc20b1dd400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /goroot/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20b1eb260, 0x7f28d4a45bf8, 0xc20c9c01c0, 0x5, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20b232580, 0x16, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).readHandshake(0xc20b232580, 0x0, 0x0, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:779 +0xe7
crypto/tls.(*Conn).clientHandshake(0xc20b232580, 0x0, 0x0)
        /goroot/src/crypto/tls/handshake_client.go:141 +0x110a
crypto/tls.(*Conn).Handshake(0xc20b232580, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:977 +0xf1
main.(*HTTPClient).Connect(0xc20800a1c0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:81 +0x2d2
main.(*HTTPClient).Send(0xc20800a1c0, 0xc20b141bbf, 0x246, 0x246, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:126 +0x1101
main.(*HTTPOutput).sendRequest(0xc20804c190, 0xc20800a1c0, 0xc20b141b80, 0x285, 0x285)
        /gopath/src/github.com/buger/gor/output_http.go:195 +0x180
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:125 +0x1b9
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 37 [select]:
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 38 [IO wait]:
net.(*pollDesc).Wait(0xc20b1c78e0, 0x72, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20b1c78e0, 0x0, 0x0)
        /goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20b1c7880, 0xc20b1dcc00, 0x400, 0x400, 0x0, 0x7f28d4a3fbb0, 0xc20b228c90)
        /goroot/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20c9c01b8, 0xc20b1dcc00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /goroot/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20b1eb1a0, 0x7f28d4a45bf8, 0xc20c9c01b8, 0x5, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20b2322c0, 0x16, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).readHandshake(0xc20b2322c0, 0x0, 0x0, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:779 +0xe7
crypto/tls.(*Conn).clientHandshake(0xc20b2322c0, 0x0, 0x0)
        /goroot/src/crypto/tls/handshake_client.go:141 +0x110a
crypto/tls.(*Conn).Handshake(0xc20b2322c0, 0x0, 0x0)
        /goroot/src/crypto/tls/conn.go:977 +0xf1
main.(*HTTPClient).Connect(0xc2080c2150, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:81 +0x2d2
main.(*HTTPClient).Send(0xc2080c2150, 0xc20b1418ff, 0x246, 0x246, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/http_client.go:126 +0x1101
main.(*HTTPOutput).sendRequest(0xc20804c190, 0xc2080c2150, 0xc20b1418c0, 0x285, 0x285)
        /gopath/src/github.com/buger/gor/output_http.go:195 +0x180
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:125 +0x1b9
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 39 [select]:
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 40 [runnable]:
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 41 [select]:
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 42 [select]:
main.(*HTTPOutput).startWorker(0xc20804c190)
        /gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 18 [syscall]:
syscall.Syscall(0x0, 0x4, 0xc209a9650b, 0xaf5, 0x50b, 0x1000, 0x0)
        /goroot/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x4, 0xc209a9650b, 0xaf5, 0xaf5, 0x50b, 0x0, 0x0)
        /goroot/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x4, 0xc209a9650b, 0xaf5, 0xaf5, 0x50b, 0x0, 0x0)
        /goroot/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208030028, 0xc209a9650b, 0xaf5, 0xaf5, 0x55ddc6, 0x0, 0x0)
        /goroot/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc208030028, 0xc209a9650b, 0xaf5, 0xaf5, 0x50b, 0x0, 0x0)
        /goroot/src/os/file.go:95 +0x91
bufio.(*Scanner).Scan(0xc2080a0080, 0xc20805a1e0)
        /goroot/src/bufio/scan.go:180 +0x688
main.(*Middleware).read(0xc2080b6000, 0x7f28d4a3fb60, 0xc208030028)
        /gopath/src/github.com/buger/gor/middleware.go:86 +0x179
created by main.NewMiddleware
        /gopath/src/github.com/buger/gor/middleware.go:41 +0x327

goroutine 19 [syscall, 1 minutes]:
syscall.Syscall6(0x3d, 0x2457, 0xc208104db4, 0x0, 0xc208066090, 0x0, 0x0, 0x7f28d4a2e000, 0xc20801e700, 0xc20a51c020)
        /goroot/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x2457, 0xc208104db4, 0x0, 0xc208066090, 0x90, 0x0, 0x0)
        /goroot/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x2457, 0xc208104dfc, 0x0, 0xc208066090, 0x0, 0x0, 0x0)
        /goroot/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc20801c6e0, 0x0, 0x0, 0x0)
        /goroot/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc20801c6e0, 0xc2080ac020, 0x0, 0x0)
        /goroot/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc2080c0000, 0x0, 0x0)
        /goroot/src/os/exec/exec.go:364 +0x23c
main.func·006()
        /gopath/src/github.com/buger/gor/middleware.go:50 +0xfa
created by main.NewMiddleware
        /gopath/src/github.com/buger/gor/middleware.go:51 +0x379

goroutine 20 [runnable]:
main.(*FileInput).Read(0xc20803aba0, 0xc208b76000, 0x500000, 0x500000, 0xc20803aba0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/input_file.go:43 +0x77
main.(*Limiter).Read(0xc20803ac00, 0xc208b76000, 0x500000, 0x500000, 0x50b, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/limiter.go:85 +0x99
main.(*Middleware).copy(0xc2080b6000, 0x7f28d4a43880, 0xc2080c60c0, 0x7f28d4a40650, 0xc20803ac00)
        /gopath/src/github.com/buger/gor/middleware.go:66 +0xf6
created by main.(*Middleware).ReadFrom
        /gopath/src/github.com/buger/gor/middleware.go:58 +0x171

goroutine 21 [chan receive]:
main.(*HTTPOutput).Read(0xc20804c190, 0xc208654000, 0x500000, 0x500000, 0x15f, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/output_http.go:174 +0x7a
main.(*Middleware).copy(0xc2080b6000, 0x7f28d4a43880, 0xc2080c60c0, 0x7f28d4a437a8, 0xc20804c190)
        /gopath/src/github.com/buger/gor/middleware.go:66 +0xf6
created by main.(*Middleware).ReadFrom
        /gopath/src/github.com/buger/gor/middleware.go:58 +0x171

goroutine 49 [chan receive]:
main.(*Middleware).Read(0xc2080b6000, 0xc20814c000, 0x500000, 0x500000, 0x285, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/middleware.go:108 +0x78
main.CopyMulty(0x7f28d4a448c0, 0xc2080b6000, 0xc2080ac000, 0x1, 0x1, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/emitter.go:48 +0xf5
created by main.Start
        /gopath/src/github.com/buger/gor/emitter.go:25 +0x273

goroutine 65 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
        /goroot/src/runtime/asm_amd64.s:2232 +0x1

**Comment by buger** [comment]
This issue fixed in latest master, release expected within this week. Thank you!
