### ISSUE TITLE
input_tcp: Limited request size

### ISSUE THREAD

**Issue by johanneswuerbach** [buger/gor#233]
When separating listening and replaying as describe here: https://github.com/buger/gor#capture-traffic-from-port I see a lot of `tcp connection: bufio.Scanner: token too long` originating from here:
https://github.com/buger/gor/blob/master/input_tcp.go#L70

Seems like golang `Scanner` can only buffer `64 * 1024` payloads
https://golang.org/pkg/bufio/#pkg-constants

**Comment by hankl** [comment]
I got the same problem.

**Comment by hankl** [comment]
Middleware will exit  from here:
https://github.com/buger/gor/blob/master/middleware.go#L105

Traffic modifier command failed: bufio.Scanner: token too long
   2015/12/24 13:50:23 output_http:0,0,0,0,0,2032
   2015/12/24 13:50:28 output_http:0,0,0,0,0,2032

**Comment by sneakybeaky** [comment]
I got the same issue, and I created a pull request with a fix. It's still pending.

As a workaround we filtered the gor capture file and removed any request larger than 64KiB. At least then the rest of the file will be replayed. Gist available at https://gist.github.com/sneakybeaky/eba26e585ac1f83301cc

**Comment by salimane** [comment]
@johanneswuerbach this has been fixed in master.
closing this.
Thanks
