### ISSUE TITLE
No interception guarantee for large payloads. Why?

### ISSUE THREAD

**Issue by nchern** [buger/gor#234]
As stated here: https://github.com/buger/gor#is-there-a-limit-for-size-of-http-request-when-using-output-http , Gor could skip large payloads.

Could you please explain this a little bit more detailed. Is it possible to fix?

**Comment by gallir** [comment]
Because the the default response buffer is 100K -> https://github.com/buger/gor/pull/249

Also, it has a serious bug which won't allow it: https://github.com/buger/gor/pull/247

Try my fork with a big buffer: https://github.com/APSL/gor (-output-http-buffer BYTES)

**Comment by buger** [comment]
Actually, the @gallir's response is not quite right. HttpClient does not have any connection with this issue. 
When you dealing with RAW_SOCKETS or Libpcap when intercepting traffic, they do not guarantee consistency. Small HTTP payloads usually fit few TCP packets, but large payloads may consist of dozens packets, and even if 1 will be missing, the message is corrupted. 

The only way to avoid it is to put Gor as a reverse proxy or explicitly send data from your app to gor.
