### ISSUE TITLE
Is the new version of gor compatible with older gor logs?

### ISSUE THREAD

**Issue by byron-hawkins** [buger/gor#236]
It looks like the gor log format has changed significantly to support middleware (#162). I've been recording traffic on a server for about a year now, using gor version 0.9.2 (b7567bbd15eb723174a0ce98201c8568e009e47a). Is the new version of gor compatible with these old logs? Or is there a way to convert them so I can use the new gor to replay my old logs? Thanks for your help.

**Comment by buger** [comment]
Sorry, I do not think you can re-use them, and we do not have a converter.
