### ISSUE TITLE
output to stdout

### ISSUE THREAD

**Issue by rgarcia** [buger/gor#242]
We'd like to run gor in a mode that logs the captured traffic to stdout. As far as I can tell this isn't possible?

The larger context is that we'd like to capture traffic logs for all of our services and store them in Cloudwatch Logs, and then create tools to pull this data down by time range and run it through gor replay.

**Comment by salimane** [comment]
@rgarcia is the output ``-output-dummy`` you are looking for ?
Thanks

**Comment by rgarcia** [comment]
Thanks @salimane! I think this works
