### ISSUE TITLE
gor crash Version: 0.10.1

### ISSUE THREAD

**Issue by GrantZheng** [buger/gor#243]
sudo ./gor --input-raw :80 --output-http "http://demo.com" --http-original-host --http-allow-url /live_get

panic: runtime error: slice bounds out of range

goroutine 18 [running]:
github.com/buger/gor/proto.Path(0xc2080ce03f, 0x12, 0x4fffc1, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/proto/proto.go:109 +0x11e
main.(*HTTPModifier).Rewrite(0xc208030020, 0xc2080ce03f, 0x12, 0x4fffc1, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/http_modifier.go:67 +0x599
main.CopyMulty(0x7f37157495e0, 0xc20803ac00, 0xc2080a6010, 0x1, 0x1, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/emitter.go:66 +0x543
created by main.Start
	/gopath/src/github.com/buger/gor/emitter.go:28 +0x447

goroutine 1 [select]:
main.Start(0x0)
	/gopath/src/github.com/buger/gor/emitter.go:33 +0x339
main.main()
	/gopath/src/github.com/buger/gor/gor.go:52 +0x200

goroutine 5 [chan receive]:
main.(*RAWInput).listen(0xc20803ac00, 0x7fff233958fb, 0x3)
	/gopath/src/github.com/buger/gor/input_raw.go:72 +0x40e
created by main.NewRAWInput
	/gopath/src/github.com/buger/gor/input_raw.go:28 +0x119

goroutine 17 [chan receive]:
main.(*HTTPOutput).workerMaster(0xc20804c3c0)
	/gopath/src/github.com/buger/gor/output_http.go:98 +0x4b
created by main.NewHTTPOutput
	/gopath/src/github.com/buger/gor/output_http.go:91 +0x2ad

goroutine 49 [select]:
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc2080c8000)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:94 +0x3e6
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:84 +0x29f

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0xc208734060, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208734060, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc208734000, 0xc208736000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7f3715748bb0, 0xc208780708)
	/goroot/src/net/fd_unix.go:269 +0x4a1
net.(*IPConn).ReadFromIP(0xc208704010, 0xc208736000, 0x10000, 0x10000, 0x2e, 0xc20877f440, 0x0, 0x0)
	/goroot/src/net/iprawsock_posix.go:82 +0x124
net.(*IPConn).ReadFrom(0xc208704010, 0xc208736000, 0x10000, 0x10000, 0x2e, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/net/iprawsock_posix.go:102 +0x12e
github.com/buger/gor/raw_socket_listener.(*Listener).readRAWSocket(0xc2080c8000)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:143 +0x2c1
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:85 +0x2b9

goroutine 5149 [select]:
main.(*HTTPOutput).startWorker(0xc20804c3c0)
	/gopath/src/github.com/buger/gor/output_http.go:123 +0x297
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 161 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1

**Comment by salimane** [comment]
this has been fixed on master.
Thanks
