### ISSUE TITLE
Not able to listen on CentOS 7

### ISSUE THREAD

**Issue by nikhilo** [buger/gor#244]
I was able to compile and create a binary on a CentOS 7 host. But I couldn't get it to listen successfully.

```
[root@ip-x-x-x-x nikhilo]# ./gor --verbose --debug --input-raw :80 --output-http "http://localhost:8080" --output-file "./requests.gor"
Version:
[DEBUG][PID 15139][1456971453162149619][1456971453162.149658ms] Listening for traffic on: :80
```

But, there's no output anywhere
```
-rw-r-----. 1 root root 0 Mar  3 02:17 requests.gor

[root@ip-10-224-5-140 nikhilo]# nc -l 8080
```

I also tried `--output-http` and `--output-file` separately
Also, I tried to debug with a echoing [HTTP server](https://gist.github.com/huyng/814831/raw/ce6f1b62965046f8f67a6386d3e93db12fd440a3/reflect.py)

**Comment by grantkl** [comment]
Do you have another service listening on port 80? GOR won't do anything with --input-raw unless that port is already open.

**Comment by nikhilo** [comment]
@grantkl yes, we do have a service already listening on 80. (But that's that traffic we want to capture, and mirror)

**Comment by salimane** [comment]
@nikhilo is there is a service running on port 80, you cannot run gor on the same port . You need to send the service traffic to another port with nginx or something where you would listen with gor

**Comment by buger** [comment]
@salimane from my point of view configuration is valid. @nikhilo can you give docker versions for CentOS 6 (which worked) and CentOS 7.

**Comment by nikhilo** [comment]
@buger we are using Docker only on CentOS 7 setup. The CentOS 6 setup which worked, does not involve Docker. The docker version we used for CentOS 7 : Docker version 1.10.3, build 20f81dd

**Comment by buger** [comment]
Also note that currently Gor works with IPv4, can it be that CentOS 7 have IPv6 by default or similar?

**Comment by buger** [comment]
Released https://github.com/buger/gor/releases/tag/v0.11.0 Now it use libpcap as interception engine, it may fix the problem.

**Comment by buger** [comment]
Just release new version https://github.com/buger/gor/releases/tag/v0.12.0 it should handle IPv6, if this were a problem.
