### ISSUE TITLE
High resource usage of gor

### ISSUE THREAD

**Issue by EasonDong** [buger/gor#251]
I'm using gor on my ubuntu server to listen on port 80 and replay to my tomcat on the same server. Port 80 receives about 50 requests per second and gor only replays part of them filtered by url, which is about 15 requests per second. However gor consumes about 50% of the CPU and over time it consumes 1.4G of memory. Is it a bug or it does need so much resource for my usage?

**Comment by buger** [comment]
Hello! I do not think it is expected. What is the average size of requests? Did you used middleware? Can you show me how you filtered by url?

**Comment by EasonDong** [comment]
The command I use is:

```
sudo gor -input-raw :80 -output-http "http://api.coolio.com" -http-allow-url /video/letv/.+\\.m3u8$ -http-allow-url /.+\\.m3u8$
```

No middleware is used, it's a very simple setup. I'm basically replaying m3u8 static file requests. port 80 also serves other json based requests, which are at most several hundreds of bytes each. However port 80 does serves a lot of static video segment files(.ts files) too by nginx(about 50 requests per second, each segment file is 500KB), which I didn't include in my request count in the original question.

**Comment by tomazin** [comment]
you have gor and nginx both on port 80?

Gor [limit for size of http request when using output-http ](https://github.com/buger/gor#is-there-a-limit-for-size-of-http-request-when-using-output-http)

I used to gor on staging env and I don't have cpu or memory issues.

**Comment by EasonDong** [comment]
gor and nginx both on port 80 because i am replaying static m3u8 file requests and all static files are served by nginx on my server. I guess it's a bit unusual but that's the requirement.

**Comment by buger** [comment]
Released https://github.com/buger/gor/releases/tag/v0.11.0, it included lot of speed improvements.

**Comment by buger** [comment]
Just release new version https://github.com/buger/gor/releases/tag/v0.12.0 it should be even more faster and consume less memory.
