### ISSUE TITLE
--output-file silently overwrites, rather than appends to, existing file

### ISSUE THREAD

**Issue by andrewthecoder** [buger/gor#259]
This is probably pretty low priority, but it would be great if Gor didn't overwrite the output file automatically without either prompting (interactive shell) or another parameter being set.

I've just been bitten by my own stupidity and lost a 3 month long log file which I hadn't backed up yet, because I assumed Gor would append to the output file, not overwrite.

**Comment by buger** [comment]
Good point, make sense append timestamp to the file name. Sorry for the troubles! I will try to handle this in next releases.

**Comment by buger** [comment]
`output-file` received lot of tuning recently https://github.com/buger/gor/wiki/Saving-and-Replaying-from-file

Now default strategy is writing in chunks, and in your case if it find file with same name, it will create new file with different chunk suffix.

**Comment by andrewthecoder** [comment]
Thanks for this, I greatly appreciate output-file getting some love!
