### ISSUE TITLE
encounter "Worker failed on write" when restart gor replayer

### ISSUE THREAD

**Issue by guilechao** [buger/gor#266]
reproduce step:

1. start replayer : ./gor --input-tcp 0.0.0.0:8450 --output-dummy aa
2. start listener : ./gor --input-raw "0.0.0.0:9080" --output-tcp "10.23.127.236:8450" 
3. hit listener : curl -X GET -vvv  http://10.23.127.236:9080/xxx
4. close replayer and restart replayer again : ./gor --input-tcp 0.0.0.0:8450 --output-dummy aa
5. hit listener : curl -X GET -vvv  http://10.23.127.236:9080/xxx

in step 5 I see below error in listener

Worker failed on write, exitings and starting new worker: write tcp 172.17.0.125:52630->10.23.127.236:8450: write: broken pipe

if restart listener can work around this issue but hope that listener can auto fix it without restart 

thanks

**Comment by buger** [comment]
What version of Gor are you using? I think this issue was fixed in latest
versions.

On Thursday, 5 May 2016, guilechao <notifications@github.com> wrote:

> reproduce step:
>
>    1. start replayer : ./gor --input-tcp 0.0.0.0:8450 --output-dummy aa
>    2. start listener : ./gor --input-raw "0.0.0.0:9080" --output-tcp "
>    10.23.127.236:8450"
>    3. hit listener : curl -X GET -vvv http://10.23.127.236:9080/xxx
>    4. close replayer and restart replayer again : ./gor --input-tcp
>    0.0.0.0:8450 --output-dummy aa
>    5. hit listener : curl -X GET -vvv http://10.23.127.236:9080/xxx
>
> in step 5 I see below error in listener
>
> Worker failed on write, exitings and starting new worker: write tcp
> 172.17.0.125:52630->10.23.127.236:8450: write: broken pipe
>
> if restart listener can work around this issue but hope that listener can
> auto fix it without restart
>
> thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/266>
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by guilechao** [comment]
both replayer and listener are version  0.11.2

**Comment by buger** [comment]
Fixed in master
