### ISSUE TITLE
Gor taking up so much resources

### ISSUE THREAD

**Issue by akurniawan** [buger/gor#267]
Hi, currently I'm running gor in my production, but once gor is turned up the cpu goes twice than usual and the memory gradually spaced out (this causes us an incident a few days ago :) ). Are these expected  from gor in production?

**Comment by buger** [comment]
Hello! Can you add more details, like what is your usual number of RPS, what is traffic look like (GET/POST), if there are large post requests like file uploads? What is Gor version your were using?

**Comment by akurniawan** [comment]
The server acts as load balancer for incoming metrics to store data in graphite, and only running haproxy underneath. 
![carbon](https://cloud.githubusercontent.com/assets/4723643/15106526/3b3405b2-15f4-11e6-873d-b9a68c41730b.png)
Above is the graph for our system.
Currently there are around 200k metrics sended from our production, so let's say there are 200k RPS
No such large incoming post/get requests.
Gover version that currently running is v0.11.2

**Comment by buger** [comment]
That's a lot, thank you. So, all the requests are POST requests with bodies containing metrics data?

**Comment by akurniawan** [comment]
Actually we're sending the metrics using TCP, so there are no POST/GET requests.
Here is command I used to intercept the requests /usr/local/bin/gor --input-raw ...:2003 --output-tcp "....:80".
Ah, I forgot one thing. There are so many  broken packages received in my staging server, are there any such way to prevent gor sending broken data?

**Comment by buger** [comment]
Well, now I see why it happens... 

Currently, Gor made to handle HTTP traffic; I did not test it on binary data like this. Well, for sure I can make Gor take care of it, but it requires some work, for example `--output-tcp` can be used only for internal communication between Gor listener and replay server. Can you tell me a bit more about this protocol?

**Comment by akurniawan** [comment]
I see, I thought gor already capable of handling plain tcp.
Well, graphite protocol is really simple, I just need to send plaintext data into graphite server with this format: <metrics_name> <value> <epoch_timestamp>, then the server will parse the request and save the data into the disk. For instance, ```echo "local.random.diceroll 4 `date +%s`" | nc -q0 ${SERVER} ${PORT}```

**Comment by buger** [comment]
Just curious, can you explain a bit your use-case? I mean graphite server have definitely simple protocol, clients are standardized (no weird user input), what are you trying to test?

**Comment by akurniawan** [comment]
Ah sure, I'm in the middle of building new graphite cluster in staging environment, and I would like to apply the new architecture into my production environment since current architecture is a little bit messy and really hard to scale. With that, I need to test the capability of my new cluster to handle the same requests as the one that currently running in production. 
As you may now, graphite consists from graphite-web, which requires http request and exactly a prefect match with gor, and carbon, which requires tcp plaintext as its input. So, basically I need a tool for handling both http and tcp as a testing medium for my new cluster

**Comment by buger** [comment]
For now I would probably recommend you to try https://github.com/session-replay-tools/tcpcopy. Thanks! 

I will ping you when situation with binary data will be better.

**Comment by akurniawan** [comment]
Hi, thanks for your recommendation!

The memory problem is still happened if I keep gor running in the long time, here is our graph monitoring showing our memory gradually decreased over time

<img width="1664" alt="screen shot 2016-05-10 at 8 14 06 pm" src="https://cloud.githubusercontent.com/assets/4723643/15147663/f3810208-16eb-11e6-97ac-07c4e96c0630.png">

Still using the same version as the one that I mentioned above.
Here's the command I used for running gor
```/usr/local/bin/gor --input-raw .....:80 --output-http http://... --http-allow-url .... --output-http-workers=30```

**Comment by buger** [comment]
I found the memory leak and working on fixing it, thanks!

**Comment by buger** [comment]
Memory leak fixed in latest master.

**Comment by buger** [comment]
Just released new version with fixes and IPv6 support https://github.com/buger/gor/releases/tag/v0.12.0

**Comment by akurniawan** [comment]
I've been using the new release version and it works, thanks!
But I believe the fix for tcp protocol hasn't fixed yet?

**Comment by buger** [comment]
Right, raw TCP replay still not implemented.
