### ISSUE TITLE
Can't get listener/replayer pair to work in release 11.2

### ISSUE THREAD

**Issue by fimbulwint** [buger/gor#268]
I've tried several setups with the listener and the replayer running on different Linux boxes and I can't get the listener to send any traffic to the replayer. Exactly the same configuration works correctly in 10.1. Gor commands are:

Listener:
```bash
[root@list-box tmp]# ./gor11.2 --verbose --input-raw :8999 --output-tcp rep-box:32722
```
Replayer:
```bash
[root@rep-box tmp]# ./gor11.2 --verbose --input-tcp :32722 --output-http destination-box:8999 --http-allow-url /appUrlHere
```

The listener keeps printing:

> 2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence
2016/05/09 11:28:00 Received packet with same sequence

Replacing the listener with version 10.1 makes it work again, I can see the traffic arriving at the 11.2 replayer and the logging messages disappear.

The machines are running CentOS 6.7

**Comment by buger** [comment]
@fimbulwint thank you for the report. Can you try to specify direct IP like `--input-raw 127.0.0.1:8999' ?
You can see list of interfaces and IP's using `ifconfig`. Thank you!

**Comment by fimbulwint** [comment]
That worked, I can see the traffic now. Using `--input-raw 0.0.0.0:8999` works too. I wasn't aware this had changed in the new version(s).

Thank you very much for the quick response.

**Comment by buger** [comment]
This is definitely not expected behavior, and I think it will fix in next
release

On Monday, 9 May 2016, fimbulwint <notifications@github.com> wrote:

> Closed #268 <https://github.com/buger/gor/issues/268>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/268#event-654372232>
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by buger** [comment]
Just release new version https://github.com/buger/gor/releases/tag/v0.12.0, now it allows you to listen on all interfaces.

**Comment by fimbulwint** [comment]
Fantastic, thanks! :)
