### ISSUE TITLE
GOR tool - How to implement at production webserver

### ISSUE THREAD

**Issue by SVLN** [buger/gor#272]
Just gone through GOR here...

Few clarification require to implement this GOR in my project.

How do we integrate GOR with webserver, do we need to copy paste the GOR over the webserver, if it yes, then where we need to paste.

How GOR will recognize the command which you have mentioned.

Not clear,could u please elaborate as well how replay server will do and to use this replay server into test environment.

**Comment by buger** [comment]
Hello! 

Gor distributed as single binary file, and for Linux you can download archive with the latest release binary here https://github.com/buger/gor/releases

On your server it may look like:
```
# This command will download archive with binary and create file gor_v0.12.0_x64.tar.gz in current directory
wget https://github.com/buger/gor/releases/download/v0.12.0/gor_v0.12.0_x64.tar.gz

# Now we need to unarchive it, this will create `gor` binary in current directory
tar -xzf gor_v0.12.0_x64.tar.gz
```

Once you have unarchived binary, you can put it to your PATH, for example copy to /usr/local/bin: `cp ./gor /usr/local/bin`, or just execute from current directory: `./gor --arguments....`

In most basic setup you can skip replay server and let it replay from the same server. Your final command will be:
```
# Assuming that you have web server running on port 80
gor --input-raw :80 --output-http http://staging_url
```

Does it make sense? Thank you!

**Comment by SVLN** [comment]
In your article stating that GOR will be listener then how gor will interact with webserver who maintain http traffic.

Should i unarchive the binary file in any of the directory.

Say for an example at D directory there do have bin file in GOR.i am not find any..please clarify in detail.

**Comment by buger** [comment]
Think about Gor more like a network analyzer, not a proxy. You do not need to include it into your web request chain. Instead it will analyze and log traffic of your app, not affecting it anyhow. 

You can unarchive binary to any directory; it does not matter. Usually, when you unarchive tar.gz file, binary with Gor should be located in the same directory as the archive and should be named `gor`.

Maybe it make sense continue discussion by sending me mail to support@gortool.com ?

Thank you!
