### ISSUE TITLE
Continuous stream of "write: broken pipe" since v11.2

### ISSUE THREAD

**Issue by fimbulwint** [buger/gor#274]
I'm trying to replace a v10.1 listener/replayer setup with a newer Gor version, but I'm finding the same issue with versions 11.2, 12.0 and 12.1.

As soon as I start the listener, I get a constant stream of `2016/05/17 10:34:03 Worker failed on write, exitings and starting new worker: write tcp ip-list:44482->ip-rep:32770: write: broken pipe` The replayer on the other hand keeps printing `Unexpected error in input tcp connection: bufio.Scanner: token too long`

All traffic seems to be affected and dropped by the replayer. A capture of the traffic taken with 10.1 shows the body in the requests remains small, never larger than 1k:
```
Content-Length: 1024
Content-Length: 20
Content-Length: 34
Content-Length: 35
Content-Length: 36
Content-Length: 38
Content-Length: 56
Content-Length: 58
Content-Length: 60
Content-Length: 62
```
The exact commands I'm using:
`gor --input-raw 0.0.0.0:8089 --output-tcp ip-rep:32770`
`gor --input-tcp :32770 --output-http rep-url --http-allow-method POST`

Restarting the processes doesn't work around the problem, nor does Gor seems to recover after more than two minutes running.

**Comment by buger** [comment]
Thank you, I found the issues, and it is fixed now! 

I'm not yet ready to make a new release, but you can use this development build: it differs only by one commit from the latest release, and should be safe to use. 

https://www.dropbox.com/s/0pienr7tbbipad2/gor_DEV-1463497005_x64.tar.gz?dl=1

**Comment by fimbulwint** [comment]
Yeah, I can't see the errors anymore and the traffic is making it to its final destination. Thank you very much for the quick response.

**Comment by buger** [comment]
Released in https://github.com/buger/gor/releases/tag/v0.13.0
