### ISSUE TITLE
does gor capture responses?

### ISSUE THREAD

**Issue by dburbridge** [buger/gor#276]
I am experimenting with gor and turned on - output-file and it looks like it is capturing both request and responses (when using --input-raw)

Is it possible to *only* capture requests? As the responses make the output file much larger than it need be for my purposes.

**Comment by buger** [comment]
Hello! I'm considering this option for the next release, it should happen
this week. Thank you!

On Wed, May 18, 2016 at 2:42 PM, dburbridge <notifications@github.com>
wrote:

> I am experimenting with gor and turned on - output-file and it looks like
> it is capturing both request and responses (when using --input-raw)
>
> Is it possible to *only* capture requests? As the responses make the
> output file much larger than it need be for my purposes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/276>
>



-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by fimbulwint** [comment]
+1

I'm sending the captured traffic over tcp to a staging replayer and I've seen huge network usage increase on production in the last version due to this (I'm just interested in requests and responses are much, much larger)

**Comment by buger** [comment]
Sure, probably make sense to turn on response capture option only if
middleware are used.

On Thursday, 19 May 2016, fimbulwint <notifications@github.com> wrote:

> +1
>
> I'm sending the captured traffic over tcp to a staging replayer and I've
> seen huge network usage increase on production in the last version due to
> this (I'm just interested in requests and responses are much, much larger)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/276#issuecomment-220297457>
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by buger** [comment]
Support for optional responses just landed master, here is pre-compiled binaries:

Linux: https://www.dropbox.com/s/29dtzttqu57cchj/gor_optional-response_x64.tar.gz?dl=1
Mac: https://www.dropbox.com/s/bpgzokknirqzlzn/gor_optional-response_mac.tar.gz?dl=1

Full featured new release moved to next week. Thanks!

**Comment by buger** [comment]
Released in https://github.com/buger/gor/releases/tag/v0.13.0
