### ISSUE TITLE
Response from server

### ISSUE THREAD

**Issue by ansham22** [buger/gor#280]
@buger . I need to ask where does responses from forwarded addresses goes. Does response from staging server where traffic is replayed goes to replay server?

**Comment by buger** [comment]
Gor is not a proxy, it does not inject itself into request pipeline,
instead it just analyze incoming network traffic. It technically can't
substitute staging response with replayer response.

It is possible to access staging response in middleware, if you need it.

On Saturday, 21 May 2016, ansham22 <notifications@github.com> wrote:

> @buger <https://github.com/buger> . I need to ask where does responses
> from forwarded addresses goes. Does response from staging server where
> traffic is replayed goes to replay server?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/280>
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by ansham22** [comment]
One more here @buger. I am a bit confused i.e replay production traffic to my staging server. Will response from staging server lands into something like /dev/null.

**Comment by buger** [comment]
Right, unless you want to reuse this data using middleware

On Saturday, 21 May 2016, ansham22 <notifications@github.com> wrote:

> One more here @buger <https://github.com/buger>. I am a bit confused i.e
> replay production traffic to my staging server. Will response from staging
> server lands into something like /dev/null.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/issues/280#issuecomment-220768162>
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by ansham22** [comment]
I will start using it and will use middle ware for intercepting response.

**Comment by buger** [comment]
Worth noticing that I'm working on functionality which will allow generate
reports by comparing staging and original responses, to detect regression
errors.

On Saturday, 21 May 2016, Leonid Bugaev <leonsbox@gmail.com> wrote:

> Right, unless you want to reuse this data using middleware
>
> On Saturday, 21 May 2016, ansham22 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> One more here @buger <https://github.com/buger>. I am a bit confused i.e
>> replay production traffic to my staging server. Will response from staging
>> server lands into something like /dev/null.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/buger/gor/issues/280#issuecomment-220768162>
>>
>
>
> --
> ---
> Sincerely yours Leonid Bugaev
> http://gortool.com - test your system with real data
>
>

-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by ansham22** [comment]
will wait for it. useful information
