### ISSUE TITLE
hi, newBuf := make([]byte, n+4)      should be newBuf := make([]byte, n+16)?

### ISSUE THREAD

**Issue by markeloff** [buger/gor#285]
hi,
listener.go 
readRAWSocket()
newBuf := make([]byte, n+4)  
   should be
newBuf := make([]byte, n+16)?

**Comment by buger** [comment]
You are right, definitely a bug! 

Raw socket now is completely optional, as libpcap is used by default, but I will fix it in the next release.

**Comment by buger** [comment]
Fixed in master

**Comment by buger** [comment]
Released in https://github.com/buger/gor/releases/tag/v0.13.0
