### ISSUE TITLE
Source IP

### ISSUE THREAD

**Issue by omersadika** [buger/gor#288]
Hi,

How can I pass the real source IP (and maybe dest IP) along with http requests?

Thanks,

**Comment by buger** [comment]
Currently it's not possible, but what are you thinking about adding X-Real-IP header to the request?

**Comment by omersadika** [comment]
For me it sounds great.
The only issue I can see is if there already header with the same name.
Maybe an option to config the header name will be awesome.

Thanks!

**Comment by buger** [comment]
Make sense! I will try to add this option into next release (expect in 1-2 weeks).

**Comment by omersadika** [comment]
Wonderful!
Thanks a lot!

**Comment by buger** [comment]
Added to master https://github.com/buger/gor/pull/296, release should happen soon.

**Comment by buger** [comment]
Released in https://github.com/buger/gor/releases/tag/v0.14.0
