### ISSUE TITLE
Allow custom HTTP verbs

### ISSUE THREAD

**Issue by huguesalary** [buger/gor#291]
Currently, GOR only allows a specific set of HTTP Verbs:

In proto/proto.go
```
var httpMethods []string = []string{
	"GET ", "OPTI", "HEAD", "POST", "PUT ", "DELE", "TRAC", "CONN",
}
```

Would it be possible to allow custom HTTP verbs as well?

**Comment by buger** [comment]
What kind of custom verbs do you mean? Can you give an example and use-case?

On Thursday, 2 June 2016, Hugues Alary <notifications@github.com> wrote:

> Currently, GOR only allows a specific set of HTTP Verbs:
>
> In proto/proto.go
>
> var httpMethods []string = []string{
>     "GET ", "OPTI", "HEAD", "POST", "PUT ", "DELE", "TRAC", "CONN",
> }
>
> Would it be possible to allow custom HTTP verbs as well?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/buger/gor/issues/291>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAA2udp1E-ZrZbewYOFBdrjnrzNmU-y1ks5qHxkFgaJpZM4Is0Ju>
> .
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by huguesalary** [comment]
I use varnish cache extensively on my website, and as such I use BAN and
PURGE HTTP verbs to invalidate cache. This is my use case.

Otherwise, although the HTTP RFC defines standard verbs, it doesn't forbid
custom ones, as such it seems, to me, GOR shouldn't explicitly restrict
HTTP verbs to a specific set.

**Comment by buger** [comment]
Well, we can solve it via using different HTTP check algorithm or just add your methods to this list. I think for now I do the last one, and if there will be such requests in future, will implement different HTTP check.

**Comment by buger** [comment]
Done https://github.com/buger/gor/commit/ae092d6a02b6253b7040237e9462a3bf8e4cc5dd :)

**Comment by buger** [comment]
Released in https://github.com/buger/gor/releases/tag/v0.14.0
