### ISSUE TITLE
Panic when listening on tun interface

### ISSUE THREAD

**Issue by Zouuup** [buger/gor#297]
Shortly after listening on vpnc interface (tun), gor panics, solution seems to be using  --input-raw-engine "raw_socket" 

panic: runtime error: index out of range

goroutine 18 [running]:
panic(0x9755c0, 0xc82000e090)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/buger/gor/raw_socket_listener.(*Listener).readPcap.func1(0xc820187cc0, 0xc8211ba0e0, 0xc8211ba0c6, 0xc8211ba00c, 0x4, 0x0, 0x0, 0xc8211bc030, 0x1, 0x1)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:353 +0x16b1
created by github.com/buger/gor/raw_socket_listener.(*Listener).readPcap
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:426 +0x2f2

**Comment by buger** [comment]
Thank you for the report!

Can you try this binary, it should give more verbose output about error:

[gor_DEV-1465537119_x64.tar.gz](https://github.com/buger/gor/files/308380/gor_DEV-1465537119_x64.tar.gz)

**Comment by Zouuup** [comment]
Version: DEV-1465537119
2016/06/10 11:49:21 Unknown packet layerPACKET: 64 bytes, wire length 64 cap length 64 @ 2016-06-10 11:49:19.959433 +0430 IRDT
- Layer 1 (64 bytes) = DecodeFailure	Packet decoding error: Unable to decode link type 12

**Comment by buger** [comment]
I made few changes, pls try this version.
[gor_tunnel-interface_x64.tar.gz](https://github.com/buger/gor/files/308727/gor_tunnel-interface_x64.tar.gz)


Thank you!

**Comment by Zouuup** [comment]
Thanks,
no panic, and unfortunately no output.
Now i get:

2016/06/10 15:09:37 Unknown packet layer PACKET: 64 bytes, wire length 64 cap length 64 @ 2016-06-10 15:09:37.331426 +0430 IRDT
- Layer 1 (20 bytes) = IPv4	{Contents=[..20..] Payload=[..44..] Version=4 IHL=5 TOS=0 Length=64 Id=61339 Flags=DF FragOffset=0 TTL=249 Protocol=TCP Checksum=31887 SrcIP=172.17.251.32 DstIP=10.20.100.70 Options=[] Padding=[]}
- Layer 2 (44 bytes) = TCP	{Contents=[..44..] Payload=[] SrcPort=46362 DstPort=8090 Seq=104164038 Ack=0 DataOffset=11 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=4380 Checksum=19146 Urgent=0 Options=[..9..] Padding=[]}

**Comment by buger** [comment]
Can you suggest me a way to replicate this issue?

**Comment by Zouuup** [comment]
hmmm...
i don't know if it's because of vpnc or not, i haven't tried other tun devices. but easiest way to try this is to boot a qemu machine, set network to tun type and try running gor on the interface while curling.

**Comment by buger** [comment]
I've read how tcpdump handle tun interfaces, and everywhere it is recommended listen on localhost instead. In your case you may try listen on all interfaces (specify only the port like ":80").
