### ISSUE TITLE
Listening on multiple port?

### ISSUE THREAD

**Issue by Zouuup** [buger/gor#298]
Won't it be cool to be able to listen on multiple ip/port addresses?
something like: 1.1.1.2:8080,8081,80 1.1.1.3:8090

**Comment by buger** [comment]
Well, actually you can already do that by using multiple --input-raw: `gor --input-raw 1.1.1.2:8080 --input-raw :8081 --input-raw :80 ...`. But this should be the same service on this ports, because capturing traffic from different apps make no much sense: you can't replay it correctly.

**Comment by Zouuup** [comment]
Thanks.

What if i use --input-raw-engine "raw_socket" for one of them? will it affect all others?

**Comment by buger** [comment]
Yes, it will affect all of them.
