### ISSUE TITLE
Panic when writing to file

### ISSUE THREAD

**Issue by Zouuup** [buger/gor#299]
gor --input-raw x:8090  --input-raw-engine "raw_socket" --input-raw y:8090 --input-raw y:8091 --input-raw y:8092 --input-raw y:8093 --output-file=requests.gor

results in:
panic: reflect: Call using main.FileOutputConfig as type *main.FileOutputConfig

goroutine 1 [running]:
panic(0x8a4d60, 0xc8211561f0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
reflect.Value.call(0x929e20, 0xb16d80, 0x13, 0xa19f80, 0x4, 0xc8211205a0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:372 +0x74a
reflect.Value.Call(0x929e20, 0xb16d80, 0x13, 0xc8211205a0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
main.registerPlugin(0x929e20, 0xb16d80, 0xc820a07cd0, 0x2, 0x2)
	/go/src/github.com/buger/gor/plugins.go:57 +0x396
main.InitPlugins()
	/go/src/github.com/buger/gor/plugins.go:120 +0xe51
main.main()
	/go/src/github.com/buger/gor/gor.go:60 +0xb95

**Comment by Zouuup** [comment]
same happens with:
gor --input-raw x:8090 --output-file=/root/requests.gor

**Comment by buger** [comment]
Sorry for the issue, here is the fixed binary, and new hot fix release should happen in few hours.

[gor_fix_output_file_x64.tar.gz](https://github.com/buger/gor/files/308734/gor_fix_output_file_x64.tar.gz)

(this binary also contains tunnel interface fixes)

**Comment by Zouuup** [comment]
Fix confirmed.
