### ISSUE TITLE
Response + Returned Data?

### ISSUE THREAD

**Issue by Zouuup** [buger/gor#302]
Thanks for the great software!

we need to be log the data returned (response payload) from web server as well, not just requests, i know that gor can track response with --input-raw-track-response, but it only includes header, not the data.

is there any workaround?

**Comment by buger** [comment]
It is intended to return response data as well. Can you tell me about your responses, do they have Transfer-Encoding: Chunked, and what average size of those responses?

**Comment by Zouuup** [comment]
no they don't, this is curl response:
HTTP/1.0 200 OK
Date: Fri, 10 Jun 2016 12:54:57 GMT
Server: WSGIServer/0.1 Python/2.7.10rc1
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=utf-8

HEEEEEEEEEEEEELLLLLLLLLLOOOOOOOOOOOOOOOO

and what i get from gor is only:
HTTP/1.0 200 OK

**Comment by Zouuup** [comment]
test webserver is simple django application that just says:
return HttpResponse('HEEEEEEEEEEEEELLLLLLLLLLOOOOOOOOOOOOOOOO')

**Comment by buger** [comment]
That's weird since this is test application, is there any chances if you can give its source code so that I can debug locally? Or at least tell which Django version did you used. 

Thank you!

**Comment by Zouuup** [comment]
ahh, it was a single 1.9.7, it was a very simple singled app django projects that just prints the httpresponse line, unfortunately it's now dead :)) if it helps, i can create another one.

**Comment by buger** [comment]
Merging this issue with #322, pls see my last comment there. Thank you!
