### ISSUE TITLE
100 Continue not merging?

### ISSUE THREAD

**Issue by joekiller** [buger/gor#307]
I have a post that contains a 100-continue. From my understanding, gor should wait for the payload and concatenate the message.

While my TCP dump shows the stream:
```
POST /solr/core/select?version=2.2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: devsolr5c01
Content-Length: 1047
Expect: 100-continue
Accept-Encoding: gzip, deflate
X-CIP: 172.30.160.21

HTTP/1.1 100 Continue

q=(test)HTTP/1.1 200 OK
```

This is what gor results in:
```
1 a74fb0f3c011cab0d27267143ce9e93bd416a93f 1466102970426448000
POST /solr/core/select?version=2.2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: devsolr5c01
Content-Length: 1047
Expect: 100-continue
Accept-Encoding: gzip, deflate
X-CIP: 172.30.160.21


```

I'll try to test some.

**Comment by buger** [comment]
Gor has special handling for 100-continue requests, basic idea is that request body comes with different TCP message, and gor have to maintain map with aliases between those 2 messages.

**Comment by joekiller** [comment]
I think the problem is in the line https://github.com/o19s/gor/blob/2e12cc0058d4620ce33c3a215ede796c0964b464/raw_socket_listener/listener.go#L580

It's expecting the last header to be "Expect: 100-continue" but it can be in any header.

Currently I plan to fix by having it scan for a double CLRF on a post and if there is one (indicating no body), scan headers for the Expect.  https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

**Comment by buger** [comment]
Definitely, make sense! And your pcap file proves your version. 
Checking for CLRF nice trick and actually make things a bit faster on most payloads. 

I would suggest using `proto.Header` function to check for header, and modify `proto.SetHeader` to remove header line if you pass empty value: basically adds support for removing headers.

**Comment by joekiller** [comment]
Okay I'll use those. I think I'll make an explicit `proto.DelHeader` because message headers may be empty.
