### ISSUE TITLE
Bash can't store null ASCII values in string

### ISSUE THREAD

**Issue by skerrwork23** [buger/gor#309]
In the bash middleware script, it might be worth adding a comment that the HTTP POST bodies that have been hex-encoded by Gor cannot contai nulls if bash middleware is used. The reason is that, after XXD call converts a hex null to an ASCII null in the script, but the ASCII null won't be stored in the bash var (they never can). So the script can only work with HTTP POST's that don't have hex nulls after Gor hex-encodes them.

I discovered this while using a variant of the bash script with incoming binary (Google protobuf) data. Some ideas/workarounds are here:

http://stackoverflow.com/questions/6570531/assign-string-containing-null-character-0-to-a-variable-in-bash

But all that's really required is maybe a comment about nulls in the script.

**Comment by buger** [comment]
I'll be frank, I did not consider using `bash` for middlewares, it was added mostly to show that you can write middleware **even in bash** :)

Well as suggest in article you can operate with nulls in bash if you use pipes:

```
echo -e "$line"       |
xxd -r -p                 | # decode
request_parser.sh | # write your custom parsing logic in this script, or inline directly
xxd -p                    | # encode back
tr -d "\\n"                | # add new line
echo                        # print back
```

I will add notice into the example :)

**Comment by skerrwork23** [comment]
Thanks!
