### ISSUE TITLE
possible to capture remote_addr ?

### ISSUE THREAD

**Issue by dburbridge** [buger/gor#315]
Would it be possible to capture the remote IP address of each request?

I would like to use Gor to test IP authentication and this would be VERY useful :)

**Comment by buger** [comment]
It is already possible in latest release, you can inject header with real ip, for example: 

`gor --input-raw-realip-header "X-Real-IP" ...`

**Comment by dburbridge** [comment]
Awesome - looks perfect, not sure how I missed that, sorry! :)
