### ISSUE TITLE
10x traffic 

### ISSUE THREAD

**Issue by ansham22** [buger/gor#316]
Hey @buger ,

It's me again.I have one question. Can I send 10X traffic through gor to my staging. I am in middle of testing capacity of my resources. Can you please help

**Comment by buger** [comment]
Hello! Yes, definitely, it is possible if you record your traffic to the file, and then replay it like this: `gor --input-file "./requests.log|1000%"` --output-http http://staging.com`. As you see I set replay speed to 1000% which is 10x.

**Comment by joekiller** [comment]
https://github.com/buger/gor/wiki/Troubleshooting might be relevant for bottlenecks that can occur when running high volumes of traffic.
