### ISSUE TITLE
Request sequence not maintained

### ISSUE THREAD

**Issue by dnissimi** [buger/gor#321]
Hi,

Is seems the sequence of my requests is not maintained (neither when using --output-stdout nor --output-file).

Is this by design?

I ask because in my test case it is important for the multiple requests to be captured and replayed in a specific order.

Thanks.

**Comment by dnissimi** [comment]
Just to clarify my test case, I am using a single client to generate a sequence of HTTP requests while 'gor' captures them to a file.  My hope is to them playback the file in a loop at an accelerated rate (for load testing).

I noticed that at the 'capture' stage, the requests are being saves (or even outputted to stdout) in a different order than they are sent.  I've confirmed this by running tcpdump in parallel and comparing the sequence.  I don't know if I'd face the same issue during 'playback', as I have yet to validate the sequence upon playback.

It would be great if:
a. requests are printed in the order they are sent
b. during playback, each worker plays the requests back in the sequence specified in the file

A suggested workaround may also help.

This is a great tool - wish I could use it effectively!

Cheers

**Comment by buger** [comment]
Hello! Well it definitely should maintain same order.

What kind of those requests, GET or POST with bodies?

Do you trigger those requests manually, or some automated way? Asking
because it can be sort of concurrency issue.

If this is dev environment is there any chance you can record pcap file
using tcpdump and send it to me?

On Thursday, 30 June 2016, dnissimi <notifications@github.com> wrote:

> Just to clarify my test case, I am using a single client to generate a
> sequence of HTTP requests while 'gor' captures them to a file. My hope is
> to them playback the file in a loop at an accelerated rate (for load
> testing).
>
> I noticed that at the 'capture' stage, the requests are being saves (or
> even outputted to stdout) in a different order than they are sent. I've
> confirmed this by running tcpdump in parallel and comparing the sequence. I
> don't know if I'd face the same issue during 'playback', as I have yet to
> validate the sequence upon playback.
>
> It would be great if:
> a. requests are printed in the order they are sent
> b. during playback, each worker plays the requests back in the sequence
> specified in the file
>
> A suggested workaround may also help.
>
> This is a great tool - wish I could use it effectively!
>
> Cheers
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/buger/gor/issues/321#issuecomment-229531262>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA2ufwuttqkqQba4ct0Ygg6zsqd5dDLks5qQxLjgaJpZM4JBsde>
> .
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by dnissimi** [comment]
These are HTTP POST with bodies.  In some cases the bodies are rather large blobs (segmented over 5-6 TCP packets)...

They are sent 'automatically' by a client application, however, the app will wait for a response before sending the next request, since the response contains a payload that is required for the subsequent request...  Latency between requests will range anywhere from 10ms to about 250ms.

I can send you a pcap via email (would rather not post here), but just to give you an idea, here is screenshot from wireshark:

![image](https://cloud.githubusercontent.com/assets/5580193/16477966/2b11c4e8-3e9f-11e6-8caf-550772ce2baf.png)

Thanks

**Comment by buger** [comment]
Thank you, send it to leonsbox@gmail.com

On Thursday, 30 June 2016, dnissimi <notifications@github.com> wrote:

> These are HTTP POST with bodies. In some cases the bodies are rather large
> blobs (segmented over 5-6 TCP packets)...
>
> They are sent 'automatically' by a client application, however, the app
> will wait for a response before sending the next request, since the
> response contains a payload that is required for the subsequent request...
> Latency between requests will range anywhere from 10ms to about 250ms.
>
> I can send you a pcap via email (would rather not post here), but just to
> give you an idea, here is screenshot from wireshark:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5580193/16477966/2b11c4e8-3e9f-11e6-8caf-550772ce2baf.png>
>
> Thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/buger/gor/issues/321#issuecomment-229565247>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA2uSgTs4K8D-BTQTwcf_hypG8Ox9k0ks5qQ1iegaJpZM4JBsde>
> .
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by dnissimi** [comment]
Done

**Comment by buger** [comment]
Issue should be fixed in master, here are binaries:

[gor_fix_body_size_mac.tar.gz](https://github.com/buger/gor/files/341281/gor_fix_body_size_mac.tar.gz)
[gor_fix_body_size_x64.tar.gz](https://github.com/buger/gor/files/341282/gor_fix_body_size_x64.tar.gz)

It was not properly computing body size for requests which had headers section from multiple TCP packets.

**Comment by dnissimi** [comment]
Simply amazed by your competence, agility and willingness to help!

I've tested your fix successfully...  Will continue tinkering!

Thanks again mate!

**Comment by buger** [comment]
Glad it worked. Thank you for the kind words!

On Thu, Jun 30, 2016 at 7:40 PM, dnissimi <notifications@github.com> wrote:

> Simply amazed by your competence, agility and willingness to help!
>
> I've tested your fix successfully... Will continue tinkering!
>
> Thanks again mate!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/buger/gor/issues/321#issuecomment-229715918>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA2uTlZ0OsCtW9K1PoBABCqyoyLntA8ks5qQ_F7gaJpZM4JBsde>
> .
>



-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by buger** [comment]
New version  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes.
