### ISSUE TITLE
Gor aggregator instance crash

### ISSUE THREAD

**Issue by lucaspouzac** [buger/gor#323]
Hi, 

I have a problem concerning usage of GOR (v0.14.1) through a replay server.

Below the test case : 

```java
JMETER --> 4500 req/s --> Server 1 : GOR (capture and forward 100% traffic) + VARNISH
                                      |----> Server 2 : GOR (aggregator instance)
                                                         |----> Server 3 : Tomcat 8080
```

I run a load test with jmeter (always the same request at 4500 req/s)

Then I run gor aggregator instance on the server 2
```bash
sudo ./gor --input-tcp :28020 --output-http "http://server3.local:8080|1%" --stats --output-http-stats > gor-server2.log 2>&1
```
Then I run gor capture and forward instance on the server 1
```bash
sudo ./gor --input-raw :6083 --output-tcp "server2.local:28020" --output-tcp-stats --stats > gor-server1.log 2>&1
```
Gor aggregator instance is killed and gor capture is also killed.

[gor-server1.txt](https://github.com/buger/gor/files/341477/gor-server1.txt)
[gor-server2.txt](https://github.com/buger/gor/files/341478/gor-server2.txt)

If I enable the cpu and memory profiling, the files remain empty.

If I run gor aggregator instance on the server 2 with the output-file option, it works correctly.
```bash
sudo ./gor --input-tcp :28020 --output-file requests.log
```

net.ipv4.tcp_* tuning has been correctly applied.

[gor-server1-test-with-output-file-on-server2.txt](https://github.com/buger/gor/files/341505/gor-server1-test-with-output-file-on-server2.txt)

**Comment by buger** [comment]
Hello! There is a chance that you hit Go bug. Crash comes from the CGO version of DNS resolver.
By default Go should use Go based version,  C one, BUT, it can use C if process can't read `/etc/resolv.conf` file, can you check if it has permissions.

Also it is possible to force Go based DNS resolver like this:
`sudo GODEBUG="netdns=go" ./gor --input-raw :6083 --output-tcp "server2.local:28020" --output-tcp-stats --stats > gor-server1.log 2>&1`

Did you compiled Gor by yourself or used pre-compiled binary?

**Comment by lucaspouzac** [comment]
Thanks for your quick response! I use pre-compiled binary. In fact, it works correctly by forcing Go based DNS resolver.

Maybe could you add this trick in your Troubleshooting section ?

**Comment by buger** [comment]
https://github.com/buger/gor/wiki/Troubleshooting#gor-is-crashing-with-following-stacktrace

**Comment by buger** [comment]
@lucaspouzac new version [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes.
And you no more need to provide ENV variable, Go DNS engine is forced while building binaries.
