### ISSUE TITLE
Input file line endings

### ISSUE THREAD

**Issue by QasimK** [buger/gor#324]
It appears gor is very strict with line endings for input files. For whatever strange reason my editor was switching the line endings to `\r\n` rather than just `\n`, and gor was just ignoring everything in the file. I suggest gor displays a warning message if this happens.

Specifically, with gor I created a `responses_0.gor` file using `--output-file`, and I can use this file with `--input-file` just fine. However, if I edited the file with my editor, and supposing it strangely did what it did with the line endings, the saved file would stop working entirely with `input-file` and not give any kind of message except `FileInput: end of file`.

I think it would be useful because these files are editable in practise.

(Also perhaps some documentation on `🐵🙈🙉`? It's quite clear what this is, but the documentation doesn't mention it)

**Comment by buger** [comment]
Hello! 

Well, while format is text friendly, it is not intended to be edited manually, and if you are doing so, you should be sure that text editor does not modify line endings (almost in every editor I know this is configurable)

Regarding monkeys, well it is a separator between 2 requests, I made such sequence have really unique string, and easily detect it.

I will update docs to include file format description.

**Comment by buger** [comment]
https://github.com/buger/gor/wiki/Saving-and-Replaying-from-file#file-format

**Comment by QasimK** [comment]
Hi @buger, the doc update works too, thanks.
