### ISSUE TITLE
listener doesn't properly account for ethernet frame smaller than 64 octets in some scanarios

### ISSUE THREAD

**Issue by joekiller** [buger/gor#325]
If an Ethernet II frame is smaller than the minimum 64 octets it is padded at the end to meet spec. Because the frame is padded after the message, the listener can pick up some of the padding as part of the TCP payload.

~~Beware of the runt frame: https://en.wikipedia.org/wiki/Ethernet_frame#Runt_frames~~ Not a runt frame.

**Comment by buger** [comment]
I think it can be a bug in gopacket library, it does not read half of
requests from pcap file you gave me, but wireshark did. Since is easy to
repeat now with your pcap file, I believe it can be fixed. Do you have any
links to specs describing this situation?

On Friday, 1 July 2016, Joseph Lawson <notifications@github.com> wrote:

> If an Ethernet II frame is smaller than the minimum 64 octets it is padded
> at the end to meet spec. Because the frame is padded after the message, the
> listener can pick up some of the padding as part of the TCP payload.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/buger/gor/issues/325>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAA2ueAduYanJ1hLMTOoD31o8y4wG1UOks5qRWDSgaJpZM4JDZG5>
> .
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by joekiller** [comment]
@buger check out https://github.com/buger/gor/pull/326 should fix it

**Comment by joekiller** [comment]
Spec references: https://wiki.wireshark.org/Ethernet see under Allowed packet lengths:

> Ethernet packets with less than the minimum 64 bytes for an Ethernet packet (header + user data + FCS) are padded to 64 bytes, which means that if there's less than 64-(14+4) = 46 bytes of user data, extra padding data is added to the packet.

Apparently those under 64 bytes are called "runt frames" and are so notorious they get a wikipedia entry: https://en.wikipedia.org/wiki/Ethernet_frame#Runt_frames

**Comment by joekiller** [comment]
Actually I guess it just pads to 60 bytes. Either way I don't think the ethernet frame can tell if it is padded or not. If the packet was parsed with the tcp library it might get the payload correctly.

**Comment by joekiller** [comment]
This primarily affects 100-continues as that hash map ends up with invalid entries because the ACK of the 100-continue ends up polluting the hash map if it is a padded Ethernet packet. Non 100-continue the program probably ended up dropping the message later.

**Comment by joekiller** [comment]
@buger I think the PR is ready to go. 

Regarding bugs in the gopacket library it looks like there aren't any bugs. It we decoded the entire TCP envelope with the gopacket library, it would do a similar check to what we do for the size of data. [ip4.go#L198-L199](https://github.com/google/gopacket/blob/e7cf983613fbf119cd715006517c827ad757e333/layers/ip4.go#L198-L199)

**Comment by buger** [comment]
New version [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes.
