### ISSUE TITLE
Feature request pcap file read support

### ISSUE THREAD

**Issue by runningman84** [buger/gor#329]
I would like to use a prerecorded pcap file as a input.

**Comment by buger** [comment]
This feature already added to the master, but not released yet!


You can use this binaries to test it out:
[gor_100_continue_multi_packet_mac.tar.gz](https://github.com/buger/gor/files/346467/gor_100_continue_multi_packet_mac.tar.gz)
[gor_100_continue_multi_packet_x64.tar.gz](https://github.com/buger/gor/files/346468/gor_100_continue_multi_packet_x64.tar.gz)


You can read pcap file like this:
```
gor --input-raw ./path-to-file.pcap --input-raw-engine pcap_file --output-stdout
```

**Comment by runningman84** [comment]
ok this works for a single file but it does not read multiple files?
```
$ ls
CUSTOMER_0.gor   CUSTOMER.dump13  CUSTOMER.dump19  CUSTOMER.dump24  CUSTOMER.dump3   CUSTOMER.dump35  CUSTOMER.dump40  CUSTOMER.dump7
CUSTOMER.dump    CUSTOMER.dump14  CUSTOMER.dump2   CUSTOMER.dump25  CUSTOMER.dump30  CUSTOMER.dump36  CUSTOMER.dump41  CUSTOMER.dump8
CUSTOMER.dump1   CUSTOMER.dump15  CUSTOMER.dump20  CUSTOMER.dump26  CUSTOMER.dump31  CUSTOMER.dump37  CUSTOMER.dump42  CUSTOMER.dump9
CUSTOMER.dump10  CUSTOMER.dump16  CUSTOMER.dump21  CUSTOMER.dump27  CUSTOMER.dump32  CUSTOMER.dump38  CUSTOMER.dump43
CUSTOMER.dump11  CUSTOMER.dump17  CUSTOMER.dump22  CUSTOMER.dump28  CUSTOMER.dump33  CUSTOMER.dump39  CUSTOMER.dump5
CUSTOMER.dump12  CUSTOMER.dump18  CUSTOMER.dump23  CUSTOMER.dump29  CUSTOMER.dump34  CUSTOMER.dump4   CUSTOMER.dump6
$ gor --input-raw "*.dump*" --input-raw-engine pcap_file --output-file CUSTOMER.gor
2016/07/05 14:55:40 *.dump*: No such file or directory
```

**Comment by buger** [comment]
I think using mergecap make sense here because it ensures that each frame will be in the right order.

**Comment by joekiller** [comment]
@buger a wiki entry for this capability would be good. This is a feature! :)

Do pcapng files work too? Might save me from having to use tcpreplay for debugging.

**Comment by buger** [comment]
@joekiller will definitely update wiki! I had problems with reading files you send me earlier, so probably pcapng support in gopacket have bugs or not supported.

**Comment by buger** [comment]
New version [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those features. Thanks!
