### ISSUE TITLE
Feature request specify input device

### ISSUE THREAD

**Issue by runningman84** [buger/gor#330]
I would like to specify the input device. My machine have multiple interfaces and it looks like the tool only captures internal traffic and no real user actions.

**Comment by buger** [comment]
Here are examples how you can run gor with multiple interfaces. 

```
# Reads all interfaces if no IP specified
gor --input-raw :80 --output-stdout

# You can specify interface instead of IP address
gor --input-raw eth0:80 --output-stdout

# It also support multiple inputs
gor --input-raw 127.0.0.1:80 --input-raw 10.0.1.5:80 --output-stdout
```

Hope it helps!

**Comment by runningman84** [comment]
In our case we have a machine with nginx on port 80/443 and apache on port 8080. Gor does not read the traffic from port 8080. Tcpdump is able to read it from port 8080. Only some traffic which is originating from the machine itself is written to the output (some cronjobs polling stuff via wget).

**Comment by buger** [comment]
How do you currently running Gor?

**Comment by runningman84** [comment]
```
gor --input-raw :8080 --output-file ./requests.gor 
```

**Comment by buger** [comment]
Listening on all interfaces should work. Is there any chance you can give me recorded `pcap` file (you can send it privately to hello@gortool.com)?

`input-raw` use BPF filters, and for example, if interface has 2 IP addresses, tcpdump filter direct equivalent will look like this (pls confirm that this command catches traffic for you, just replace with your IP's)
``
tcpdump tcp dst port 8080 and (dst host 127.0.0.1 OR dst host 10.0.2.5)
``

**Comment by C0RD** [comment]
Hi, I work with @runningman84 on this. 

I talk about a machine which has an loopback-Interface "lo" with 127.0.0.1 and an Ethernet-Interface eth0 with IP $PublicIP.

We have nginx on Port $PublicIP:80 which does our ssl-offloading, and we forward the decoded traffic on to an Apache running on $PublicIP:8080. (NOT to 127.0.0.1:8080)

If we now sniff with gor for Port :8080 we only see the Traffic that comes from the outside directly to $PublicIP:8080 and the Traffic to 127.0.0.1:8080. We can't see the Traffic that comes from $PublicIP (Nginx) to $PublicIP:8080 (Apache) with gor.

If we tcpdump Interface 'lo' we see those Packages:

```
$ tcpdump -n -i lo port 8080
11:19:10.492971 IP $PublicIP.59705 > $PublicIP.8080: S 3805346785:3805346785(0) win 32792 <mss 16396,sackOK,timestamp 992220457 0,nop,wscale 7>
11:19:10.492979 IP $PublicIP.8080 > $PublicIP.59705: S 119175661:119175661(0) ack 3805346786 win 32768 <mss 16396,sackOK,timestamp 992220457 992220457,nop,wscale 7>
[...]

```
So I think gor builds its filter, that it only captures the configured IPs on an Interface. It looks on lo for Packages with src or dst 127.0.0.1 and on eth0 for Packages with src or dst $PublicIP.  But if src and dst is the same Linux uses the loopback, and not eth0.

Correct? If still needed i can send you a pcap-file.

**Comment by buger** [comment]
I did not know that it is using loopback when IP's match, even for different interfaces. I think this should be our problem, will prepare the patch.

**Comment by C0RD** [comment]
Yes i see the packages now. Thank you.

**Comment by buger** [comment]
New version [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes. Thanks!

**Comment by sandys** [comment]
@buger i apologize at commenting here, but im having similar trouble with latest gor.

I'm running Hugo (a static webserver) on port 1313 and actually testing "curl localhost:1313". gor is being run as "sudo ./gor --input-raw :1313 --output-stdout  --verbose" and tcpdump is run as "sudo tcpdump -i lo -s 1500 "port 1313"

gor is showing no output, however tcpdump is properly dumping requests. this is the tcpdump output - https://pastebin.com/Qg3Lyjwf

what am I doing wrong ?
