### ISSUE TITLE
update to latest elasticgo

### ISSUE THREAD

**Issue by joekiller** [buger/gor#331]
As noted in other tickets, the Elasticsearch output is broken. The project should be updated to use the latest elasticgo and godep to manage the dependencies.

**Comment by buger** [comment]
Frankly, I thought about Elasticsearch as Pro option, because managing and testing third parties takes a lot of time and effort. Previous ES integration was written by one of the contributors, and it broke a long time ago without support. Currently, I even do not include it into the docs.

What do you think about such approach?

PS.
Regarding dependencies I'll probably prefer vendoring (maybe with git submodules).

**Comment by joekiller** [comment]
I don't mind updating it to the latest. Git submodules is okay but godeps imo is better to solve the problem as each end up with trees in your project. It seems more natural for making go work.

Being that it was a community contribution and the community has slowly updated it, I'd leave it in. Perhaps note that it is a community supported module so YMMV etc.

**Comment by buger** [comment]
If you are willing to make ES integration work, I'm ok to leave it as basic feature (make sense since it was added before announcing Pro).

Regarding `godep` I just want to avoid any external tools, and vendoring Go experiment was success and now this feature supported by default.

**Comment by joekiller** [comment]
Okay. I'll check out vendoring in Go and try to get that working.

PS I successfully got the elasticsearch output working with the latest elastigo here: https://github.com/o19s/gor/tree/elastigo

I branched off #326 as it is related to my immediate work. I'll make it totally separate. 

    docker run --name elasticsearch -p 9200:9200 -p 9300:9300 -d elasticsearch -Des.network.bind_host=0.0.0.0 -Dhttp.cors.enabled=true -Dhttp.cors.allow-origin="*"
    docker run --name kibana --link elasticsearch:elasticsearch -p 5601:5601 -d kibana

and then with `-output-http-elasticsearch localhost:9200/gor` I can see:

![image](https://cloud.githubusercontent.com/assets/1022919/16626693/0c558886-4378-11e6-870c-7cc8de323e5c.png)

**Comment by buger** [comment]
Cool, thanks!

**Comment by buger** [comment]
I'm not an ES expert, what is the best way to store responses in ES as well? Can you suggest schema and basic architecture?

**Comment by joekiller** [comment]
Yeah I'll make that another issue.

**Comment by buger** [comment]
New version [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes. Thanks!
