### ISSUE TITLE
Store Responses in ES

### ISSUE THREAD

**Issue by joekiller** [buger/gor#332]
We'd like to store responses in ES as well. A schema and basic architecture is needed.

**Comment by joekiller** [comment]
Per https://github.com/buger/gor/issues/331#issuecomment-230840909 I think it may be easiest to just insert the response body into the [ESRequestResponse struct](https://github.com/buger/gor/blob/6647481fe07061bc90be6db55611dd34179d7c6c/elasticsearch.go#L28)

We could also try to support some of the most common response headers if we wanted: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Response_fields

**Comment by joekiller** [comment]
We could just use the (binary field type)[https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html] and dump the response and figure out other stuff later

**Comment by buger** [comment]
The problem with responses that they are arriving asynchronously from requests, so we have two options: inside ES plugin for each request wait for the response, and only after it received: send to ES. Alternative is to send responses separately.

**Comment by joekiller** [comment]
Okay that makes more sense. I didn't realize that the original response was being monitored or recorded. I'll take a look but if you have a quick link to it that'll help.

**Comment by buger** [comment]
https://github.com/buger/gor/wiki/Capturing-and-replaying-traffic#tracking-responses

**Comment by joekiller** [comment]
Thanks!

**Comment by buger** [comment]
Will close it for now
