### ISSUE TITLE
Gor exits with a trace on slice bounds out of range error

### ISSUE THREAD

**Issue by grafov** [buger/gor#335]
After a long run (approximtely one day) gor exits with trace:

panic: runtime error: slice bounds out of range

goroutine 101 [running]:
panic(0x9758c0, 0xc8200100e0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/buger/gor/proto.Path(0xc82132e03f, 0x6028, 0x4fffc1, 0x0, 0x0, 0x0)
        /go/src/github.com/buger/gor/proto/proto.go:194 +0xf8
main.(*HTTPModifier).Rewrite(0xc8212b4da8, 0xc82132e03f, 0x6028, 0x4fffc1, 0x0, 0x0, 0x0)
        /go/src/github.com/buger/gor/http_modifier.go:67 +0x651
main.CopyMulty(0x7f14d06de800, 0xc82008c2a0, 0xc82130c080, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/buger/gor/emitter.go:73 +0x601
created by main.Start
        /go/src/github.com/buger/gor/emitter.go:28 +0x5f7

There are several gor instances on different hosts falled down with this error. They all was run with args like:

    gor --input-raw :8888 --output-http http://localhost:9999 --http-allow-url somestrhere

**Comment by buger** [comment]
Hello! Which version of gor did you used?

On Friday, 8 July 2016, Alexander I.Grafov <notifications@github.com> wrote:

> After a long run (approximtely one day) gor exits with trace:
>
> panic: runtime error: slice bounds out of range
>
> goroutine 101 [running]:
> panic(0x9758c0, 0xc8200100e0)
> /usr/local/go/src/runtime/panic.go:481 +0x3e6
> github.com/buger/gor/proto.Path(0xc82132e03f, 0x6028, 0x4fffc1, 0x0, 0x0,
> 0x0)
> /go/src/github.com/buger/gor/proto/proto.go:194 +0xf8
> main.(*HTTPModifier).Rewrite(0xc8212b4da8, 0xc82132e03f, 0x6028, 0x4fffc1,
> 0x0, 0x0, 0x0)
> /go/src/github.com/buger/gor/http_modifier.go:67 +0x651
> main.CopyMulty(0x7f14d06de800, 0xc82008c2a0, 0xc82130c080, 0x1, 0x1, 0x0,
> 0x0)
> /go/src/github.com/buger/gor/emitter.go:73 +0x601
> created by main.Start
> /go/src/github.com/buger/gor/emitter.go:28 +0x5f7
>
> There are several gor instances on different hosts falled down with this
> error. They all was run with args like:
>
> gor --input-raw :8888 --output-http http://localhost:9999 --http-allow-url somestrhere
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/buger/gor/issues/335>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAA2uVlyI6f4dlEtjwV0eS2TpdiYBMCvks5qTkMpgaJpZM4JH_Ox>
> .
>


-- 
---
Sincerely yours Leonid Bugaev
http://gortool.com - test your system with real data

**Comment by grafov** [comment]
Version: v0.14.1

**Comment by buger** [comment]
Can you try this binary, i think this issues should be fixed in master:
[gor_fix_http_disallow_header_mac.tar.gz](https://github.com/buger/gor/files/394353/gor_fix_http_disallow_header_mac.tar.gz)
[gor_fix_http_disallow_header_x64.tar.gz](https://github.com/buger/gor/files/394352/gor_fix_http_disallow_header_x64.tar.gz)

**Comment by grafov** [comment]
Thank you. I'll try and report you if problem occurs again.
