### ISSUE TITLE
Gor doubles requests?

### ISSUE THREAD

**Issue by C-Pro** [buger/gor#338]
Hi! I am new to gor, and trying to mirror incoming traffic from nginx reverse proxy to some service on localhost.

`sudo ./gor --input-raw :80 --output-http="http://localhost:8070"`

But my service on 8070 gets each request twice as if gor mirrors both input traffic to nginx and its output to remote upstream also on 80 port, but on another ip. Is it ok? Shoud I filter it somehow?

**Comment by buger** [comment]
Hello! It sounds like a bug which was already fixed in master, but did not released yet. 

Can you try this binary?
https://www.dropbox.com/s/y8elp0ofs59k1rf/gor_100_continue_multi_packet_x64.tar.gz?dl=0

**Comment by C-Pro** [comment]
Looks like it fixed the problem, but i have low traffic right now. There was only two requests so far. I'll look again later.

**Comment by C-Pro** [comment]
Yes. No doubling now!

**Comment by buger** [comment]
Cool!

**Comment by joekiller** [comment]
@buger what commit fixed the bug? Pure curiosity.

**Comment by buger** [comment]
@joekiller I think this one https://github.com/buger/gor/commit/1ed8691b38016648870896d2359703db4113febb

**Comment by buger** [comment]
New version [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes. Thanks!
