### ISSUE TITLE
Packet integrity

### ISSUE THREAD

**Issue by zweite** [buger/gor#339]
https://github.com/buger/gor/blob/master/http_client.go#L120

Whether it will make the data package is not complete ?
Or just ignore it ?

**Comment by buger** [comment]
Hello! Http is bi-directional protocol, and it should not send data to socket until I send request. So this should be always "empty" read. 

To ensure that there no will be malformed data, once request is made it ensure that ALL the data will be read from the socket, leaving response buffer empty.

**Comment by joekiller** [comment]
We may want to specify that Go Replay is a http 1.1 implementation. See https://tools.ietf.org/html/rfc2616#section-8.1.2 for more info about 1.1 being persistent by default.
