### ISSUE TITLE
Multiple input files not recognized

### ISSUE THREAD

**Issue by mimmozzo** [buger/gor#342]
Hi,

thanks for this tool! Doing some tests, I am not able to read from multiple files, it outputs "Required at least 1 input and 1 output": 

> ps@ps-vm:~/tmp/gor$ ls -l requests-2016072012.log_*
> -rw-r----- 1 root root 5071 Jul 20 12:15 requests-2016072012.log_0.gz
> -rw-r----- 1 root root 5071 Jul 20 14:54 requests-2016072012.log_1.gz
> ps@ps-vm:~/tmp/gor$ sudo ./gor --input-file requests-2016072012.log_*.gz --output-file replay.log 
> Version: v0.14.1
> 2016/07/20 14:55:12 Required at least 1 input and 1 output
> ps@ps-vm:~/tmp/gor$ sudo ./gor --input-file requests-2016072012.log_0.gz --output-file replay.log  
> Version: v0.14.1 [works, interrupted manually]
> ^Cps@ps-vm:~/tmp/gor$ sudo ./gor --input-file requests-2016072012.log_1.gz --output-file replay.log 
> Version: v0.14.1 [works, interrupted manually]

[Here](https://github.com/buger/gor/wiki/Saving-and-Replaying-from-file#replaying-from-multiple-files) it says that Gor should read from all the files in lexicographical order. Could you help me?
Thanks, best

Domenico

**Comment by buger** [comment]
Hello! 

Try to wrap it into quotes: sudo ./gor --input-file "requests-2016072012.log_*.gz" --output-file replay.log

**Comment by buger** [comment]
Hello Just following up!

**Comment by im-bart** [comment]
Confirming that quotes will get rid of said warning `Required at least 1 input and 1 output`, but it will stop and hang at the first file (in the directory). OS X binary, version 0.16.1.

**Comment by buger** [comment]
Yes, Mac version have lock somewhere, Linux is not affected.
