### ISSUE TITLE
GOR Aggregator - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lucaspouzac** [buger/gor#345]
Hi, 

When I run gor aggregator in output-file mode, a runtime error is thrown after few minutes.

```
sudo GODEBUG="netdns=go" ./gor --input-tcp :28020 --output-file "/var/log/gor/%Y%m%d%H-requests.log"
```

I use a latest binary (0.14.1)

```
Version: v0.14.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x4169b9]

goroutine 7 [running]:
panic(0x9758c0, 0xc8200140e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*FileOutput).flush(0xc82000a460)
	/go/src/github.com/buger/gor/output_file.go:211 +0x139
main.NewFileOutput.func1(0xc82000a460)
	/go/src/github.com/buger/gor/output_file.go:57 +0x36
created by main.NewFileOutput
	/go/src/github.com/buger/gor/output_file.go:59 +0x96
```

**Comment by buger** [comment]
Hello! Just to confirm, this happens to RRO version as well?

**Comment by lucaspouzac** [comment]
With this file : https://github.com/buger/gor/releases/download/v0.14.1/gor_v0.14.1_x64.tar.gz

**Comment by buger** [comment]
I believe this issue was already fixed in master (but not yet released, soon..) and in v0.14.1 PRO version as well. 

You can try this pre-compiled binary based on latest master https://www.dropbox.com/s/y8elp0ofs59k1rf/gor_100_continue_multi_packet_x64.tar.gz?dl=0

**Comment by buger** [comment]
(i was writing about PRO above assuming that you already have PRO, sorry :) )

**Comment by lucaspouzac** [comment]
Thanks, it's correctly fixed on latest master.

**Comment by thenayr** [comment]
Will there be a new release cut with this fix soon?

**Comment by buger** [comment]
@thenayr yes, next week.

**Comment by buger** [comment]
@lucaspouzac @thenayr new version  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes.
