### ISSUE TITLE
Gzip payload seems to be broken

### ISSUE THREAD

**Issue by anioool** [buger/gor#347]
Hi,

I am trying to decompress gzipped payload from responses, but each time I am receiving the same error:
zlib.error: Error -3 while decompressing: incorrect header check. Script is in python and for test purpose is very easy.

`import StringIO
from httplib import HTTPMessage
import gzip
import zlib

f = open('sample3')

gor_header=f.readline()
http_header=f.readline()

#print gor_header
#print http_header

msg = HTTPMessage(f,0)
http_body = msg.fp.read()

print http_body

body_stream = StringIO.StringIO(http_body)

zliber = zlib.decompressobj(16+zlib.MAX_WBITS)
data = zliber.decompress(http_body)
`

Sample file contains single response with gor header, http header and payload without the last line which is treated as separator.

Thanks in advance for help,
Adam

**Comment by buger** [comment]
Hello! Is there any chance you can share this sample file, so I can replicate issue?

**Comment by buger** [comment]
Hello! Just following up.
