### ISSUE TITLE
--input-raw doesn't work?

### ISSUE THREAD

**Issue by amirsch** [buger/gor#349]
I've downloaded the latest binaries, and tried running the most basic example:
sudo ./gor --input-raw :8000 --output-stdout

But it didn't capture any http traffic, so I tried switching things a bit and used --input-http, and for some reason it worked (though it has no mention in the documentation). Has something changed?

**Comment by buger** [comment]
Hello! I think you misunderstood a bit how it works. You should have an application running on on port 8000 before running Gor: it analyzes traffic of your application.

`--input-http` is quite different, and frankly, will be removed from next version. It was made to redirect traffic from nginx or similar but never worked as expected.
