### ISSUE TITLE
output-file stops writing files

### ISSUE THREAD

**Issue by lucaspouzac** [buger/gor#354]
Hi, 

Sometimes, the gor aggregagor process stops writing requests files and waits log rotation to resume.

Version: fix_splitted_headers

{code:title=gor aggregator process}
/usr/sbin/gor --input-tcp :28020 --output-file /var/log/gor/%Y%m%d%H-requests.log --output-file-append --stats --output-http-stats
{code}

{code}
-rw-r-----  1 root root   3015194866 août   3 21:00 2016080320-requests.log
-rw-r-----  1 root root    457647120 août   3 21:10 2016080321-requests.log
-rw-r-----  1 root root   1724749432 août   3 22:48 2016080322-requests.log
-rw-r-----  1 root root   1536055679 août   4 00:00 2016080323-requests.log
-rw-r-----  1 root root   1035549726 août   4 01:00 2016080400-requests.log
-rw-r-----  1 root root    685442886 août   4 02:00 2016080401-requests.log
-rw-r-----  1 root root    515670842 août   4 03:00 2016080402-requests.log
-rw-r-----  1 root root    440843406 août   4 04:00 2016080403-requests.log
-rw-r-----  1 root root    432366561 août   4 05:00 2016080404-requests.log
-rw-r-----  1 root root    491169649 août   4 06:00 2016080405-requests.log
-rw-r-----  1 root root    764889554 août   4 07:00 2016080406-requests.log
-rw-r-----  1 root root    397024171 août   4 07:20 2016080407-requests.log
-rw-r-----  1 root root    912227205 août   4 08:20 2016080408-requests.log
{code}

{code:title:gor listen process}
/usr/sbin/gor --input-raw :80 --output-tcp replay.local:28020|100%  --output-tcp-stats --stats
{code}

{code:title=Log gor listen between 7h20 and 7h26 am}
2016/08/04 07:19:36 output_tcp:0,0,0,684,136,22
2016/08/04 07:19:41 output_tcp:0,0,0,675,135,22
2016/08/04 07:19:46 output_tcp:0,0,0,660,132,22
2016/08/04 07:19:51 output_tcp:0,0,0,524,104,22
2016/08/04 07:19:56 output_tcp:0,0,0,646,129,22
2016/08/04 07:20:01 output_tcp:0,0,0,541,108,22
2016/08/04 07:20:06 output_tcp:0,0,0,778,155,22
2016/08/04 07:20:11 output_tcp:0,0,0,753,150,22
2016/08/04 07:20:16 output_tcp:0,0,0,652,130,22
2016/08/04 07:20:21 output_tcp:0,0,0,663,132,22
2016/08/04 07:20:26 output_tcp:0,0,0,515,103,22
2016/08/04 07:20:31 output_tcp:0,0,0,649,129,22
2016/08/04 07:20:36 output_tcp:0,0,0,541,108,22
2016/08/04 07:20:41 output_tcp:0,0,0,537,107,22
2016/08/04 07:20:46 output_tcp:0,0,0,562,112,22
2016/08/04 07:20:51 output_tcp:0,0,0,532,106,22
2016/08/04 07:20:56 output_tcp:0,0,0,547,109,22
2016/08/04 07:21:01 output_tcp:0,0,0,553,110,22
2016/08/04 07:21:06 output_tcp:0,0,0,553,110,22
2016/08/04 07:21:11 output_tcp:0,0,0,675,135,22
2016/08/04 07:21:16 output_tcp:0,0,0,561,112,22
2016/08/04 07:21:21 output_tcp:0,0,0,559,111,22
2016/08/04 07:21:26 output_tcp:0,0,0,409,81,22
2016/08/04 07:21:31 output_tcp:0,0,0,519,103,22
2016/08/04 07:21:36 output_tcp:0,0,0,684,136,22
2016/08/04 07:21:41 output_tcp:0,0,0,677,135,22
2016/08/04 07:21:46 output_tcp:0,0,0,545,109,22
2016/08/04 07:21:51 output_tcp:0,0,0,419,83,22
2016/08/04 07:21:56 output_tcp:0,0,0,683,136,22
2016/08/04 07:22:01 output_tcp:0,0,0,544,108,22
2016/08/04 07:22:06 output_tcp:0,1,22,430,86,22
2016/08/04 07:22:11 output_tcp:0,0,0,521,104,22
2016/08/04 07:22:16 output_tcp:0,0,0,672,134,22
2016/08/04 07:22:21 output_tcp:0,0,0,399,79,22
2016/08/04 07:22:26 output_tcp:0,0,0,558,111,22
2016/08/04 07:22:31 output_tcp:0,0,0,682,136,22
2016/08/04 07:22:36 output_tcp:0,0,0,514,102,22
2016/08/04 07:22:41 output_tcp:0,0,0,664,132,22
2016/08/04 07:22:46 output_tcp:0,0,0,515,103,22
2016/08/04 07:22:51 output_tcp:0,0,0,557,111,22
2016/08/04 07:22:56 output_tcp:0,0,0,675,135,22
2016/08/04 07:23:01 output_tcp:0,0,0,533,106,22
2016/08/04 07:23:06 output_tcp:0,0,0,543,108,22
2016/08/04 07:23:11 output_tcp:0,0,0,654,130,22
2016/08/04 07:23:16 output_tcp:0,0,0,539,107,22
2016/08/04 07:23:21 output_tcp:0,0,0,638,127,22
2016/08/04 07:23:26 output_tcp:0,0,0,548,109,22
2016/08/04 07:23:31 output_tcp:0,0,0,529,105,22
2016/08/04 07:23:36 output_tcp:0,0,0,655,131,22
2016/08/04 07:23:41 output_tcp:0,0,0,518,103,22
2016/08/04 07:23:46 output_tcp:0,0,0,528,105,22
2016/08/04 07:23:51 output_tcp:0,0,0,628,125,22
2016/08/04 07:23:56 output_tcp:0,0,0,511,102,22
2016/08/04 07:24:01 output_tcp:0,0,0,639,127,22
2016/08/04 07:24:06 output_tcp:0,0,0,603,120,22
2016/08/04 07:24:11 output_tcp:0,0,0,541,108,22
2016/08/04 07:24:16 output_tcp:0,0,0,549,109,22
2016/08/04 07:24:21 output_tcp:0,0,0,535,107,22
2016/08/04 07:24:26 output_tcp:0,0,0,552,110,22
2016/08/04 07:24:31 output_tcp:0,0,0,659,131,22
2016/08/04 07:24:36 output_tcp:0,0,0,533,106,22
2016/08/04 07:24:41 output_tcp:0,0,0,542,108,22
2016/08/04 07:24:46 output_tcp:0,0,0,665,133,22
2016/08/04 07:24:51 output_tcp:0,0,0,524,104,22
2016/08/04 07:24:56 output_tcp:0,0,0,536,107,22
2016/08/04 07:25:01 output_tcp:0,0,0,535,107,22
2016/08/04 07:25:06 output_tcp:0,0,0,573,114,22
2016/08/04 07:25:11 output_tcp:0,0,0,672,134,22
2016/08/04 07:25:16 output_tcp:0,0,0,549,109,22
2016/08/04 07:25:21 output_tcp:0,0,0,552,110,22
2016/08/04 07:25:26 output_tcp:0,0,0,618,123,22
2016/08/04 07:25:31 output_tcp:0,0,0,526,105,22
2016/08/04 07:25:36 output_tcp:0,0,0,542,108,22
2016/08/04 07:25:41 output_tcp:0,0,0,664,132,22
2016/08/04 07:25:46 output_tcp:0,0,0,506,101,22
2016/08/04 07:25:51 output_tcp:0,0,0,671,134,22
2016/08/04 07:25:56 output_tcp:0,0,0,653,130,22
2016/08/04 07:26:01 output_tcp:0,0,0,546,109,22

**Comment by lucaspouzac** [comment]
System graph with disk activity. 

![cdvmgor01t-disk-vda-disk_octets](https://cloud.githubusercontent.com/assets/758899/17401413/cbb0051c-5a4d-11e6-8273-ab6e9ea3e74f.png)

**Comment by lucaspouzac** [comment]
System graph with network activity
![cdvmgor01t-interface-eth0-if_octets](https://cloud.githubusercontent.com/assets/758899/17401686/354715be-5a4f-11e6-860a-732728de3fc0.png)

**Comment by buger** [comment]
Hello! Sorry for the late response. I made few fixed, try same binaries as here in the last comment: https://github.com/buger/gor/issues/353

Thank you for the detailed feedback!

**Comment by lucaspouzac** [comment]
No problems found with the latest version (v0.15). Thanks.
