### ISSUE TITLE
v0.15.0 doesn't capture POST requests

### ISSUE THREAD

**Issue by mozz100** [buger/gor#359]
I spent a long time trying to understand why I'm not seeing POST requests with gor v0.15.0.  I think it's a bug: versions 0.14.0 and 0.14.1 both behave as I'd expect.

What does work in v0.15.0 - I can see http GET requests.  I can see the responses to GET and POST requests using --input-raw-track-response.

What doesn't work: I never see http POST requests.

My setup: nginx frontend handling SSL termination.  Requests proxied to Django running as  upstream http server on port 5012.

I've only tested with GET and POST requests so far.  I'll have to use v0.14.1 for the moment.  Is this a bug or am I missing something?  Here's my commands:

    >$ sudo gor-v0.15.0/gor --input-raw :5012 --verbose --output-stdout --debug
    [DEBUG][PID 8023][1471865971976431656][1471865971976.431641ms] Listening for traffic on: :5012
    Version: v0.15.0

Now I make a POST request - I see nothing.  Trying previous version (downloaded to adjacent folder):

    $ sudo gor-v0.14.1/gor --input-raw :5012 --verbose --output-stdout --debug
    [DEBUG][PID 8035][1471866034927930023][1471866034927.930176ms] Listening for traffic on: :5012
    Version: v0.14.1

Make a POST request.  gor works and shows me this.  So I think the previous version was fine:

    [DEBUG][PID 8035][1471866079703993530][44776.063507ms] [EMITTER] input: 1 ab0e47d72663769250d401c523387079bc4c95c1 1471866079703955328
    POST /barcode_test/ HTTP/1.0
    Host: staging.mywebsite.com
    X-Forwarded-Protocol: https
    Connection: close
    Content-Length: 69
    User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Referer: https://staging.mywebsite.com/barcode_tes 750 from: Intercepting traffic from: :5012
    1 ab0e47d72663769250d401c523387079bc4c95c1 1471866079703955328
    POST /barcode_test/ HTTP/1.0
    Host: staging.mywebsite.com
    X-Forwarded-Protocol: https
    Connection: close
    Content-Length: 69
    User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Referer: https://staging.mywebsite.com/barcode_test/
    Cookie: csrftoken=94DcitWBXZKm6ifDBr5Z8SzDwCE3rTJI; sessionid=wbt44qg46xmy0v18qej6aaahxyt94j80
    Upgrade-Insecure-Requests: 1
    Content-Type: application/x-www-form-urlencoded    

    csrfmiddlewaretoken=94DcitWBXZKm6ifDBr5Z8SzDwCE3rTJI&barcodes=TESTGOR

**Comment by buger** [comment]
Hello! Thank you for the detailed report! Any chance you can give me `pcap` file recording (you can do it using tcpdump), so I can create repeatable test case.

Thank you!

**Comment by mozz100** [comment]
Thanks for quick response.  I've never used `tcpdump` before - currently squinting at its man page.  If you could share the command I need to run, I should be able to capture things and share with you (maybe not in public but some way or another)

**Comment by buger** [comment]
Sure! `tcpdump -s 0 5012 -i any -w mycap.pcap`

**Comment by mozz100** [comment]
I seemed to have to do `tcpdump -s 0 -i any -w mycap.pcap 'port 5012'` to get it to work.  I have a file now.  May I send the file to your gmail address?  Prefer not to share with the whole world (actually it's probably harmless; I just don't want to have to vet it)

**Comment by buger** [comment]
Sure! leonsbox@gmail.com

**Comment by cpejlgc** [comment]
I met the same problem

$  gor --input-raw :8008 --output-http="http://192.168.1.12:8008

POST /pay/oppopay HTTP/1.1
User-Agent: Java/1.8.0_45
Host: 127.0.0.1:3000
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-type: application/x-www-form-urlencoded
Content-Length: 424

GET /pay/igop?userId=1154343403&key=JS000d91484061985613792502531&cpId=741589&cpServiceId=658916048419&channelId=40228007&p=&region=100&Ua=OPPO+R9tm HTTP/1.1
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 127.0.0.1:3000
`

**Comment by buger** [comment]
I finally found the issue and hopefully fixed it thanks to your feedback, pls try this binary:

[gor_fix_connection_close_x64.tar.gz](https://github.com/buger/gor/files/447262/gor_fix_connection_close_x64.tar.gz)

**Comment by mozz100** [comment]
Looks good: I can see POST requests now, when previously they were not being picked up.  Thanks!

**Comment by buger** [comment]
Just released https://github.com/buger/gor/releases/tag/v0.15.1

**Comment by pmancaux** [comment]
hello

I m using 0.16.1 and i have same problem,
I have an apache on port 80 and a JBOSS on port 8083, i would like to capture traffic on 8083.

so i launch with 

```
./goreplay --input-raw :8083 --output-http="http://slnxsncfcots04.ntes.fr.sopra:8080" -verbose -debug --output-stdout
[DEBUG][PID 31229][1529480721456942479][1529480721456.942627ms] Listening for traffic on: :8083
Version: 0.16.1
```

when i send get on apache like this :

http://myhost:80/api/provider-api/import

i can see :

```
GET /provider-api//import HTTP/1.1
Host: myhost:80
User-Agent: PostmanRuntime/7.1.5
Accept: */*
accept-encoding: gzip, deflate
Correlation-ID: WyoGjH8AAQEAACiKmMcAAAAW
...
...
Connection: Keep-Alive

```
but when i doing same request with a POST, i don't see anything, i try with the version :

```
[DEBUG][PID 20916][1529480654828115498][1529480654828.115479ms] Listening for traffic on: lo:8083
Version: fix_connection_close
```

but same problem.

did you have an issue?

here is my pcap file with tcpdump capture on port 8083 with the post request

[mycap.tar.gz](https://github.com/buger/goreplay/files/2118350/mycap.tar.gz)


thanks

**Comment by Beslist-AA** [comment]
Where is the windows version? It's suddenly not supported anymore?
