### ISSUE TITLE
v0.15.0: middleware format inconsistency

### ISSUE THREAD

**Issue by koendc** [buger/gor#363]
It looks like the middleware format in 0.15.0 has changed. The header field now contains the latency, but it appears that the replayed response header is not correct:

Request header:
`1 5b66e909b9f735763b4a546ed80380a1b008601b 1472642122813485697
`
Original response header:
`2 0eb46160a20d81847ea997f2187426a35d143fba 1472642122927395255 6856430
`
Replayed response header:
`3 5b66e909b9f735763b4a546ed80380a1b008601b 15006841726 1472642122921006198`

**Comment by buger** [comment]
Thank you so much for reporting!
Should be fixed in latest master, and here is binary: 
[gor_fix_replayed_header_x64.tar.gz](https://github.com/buger/gor/files/447293/gor_fix_replayed_header_x64.tar.gz)

**Comment by buger** [comment]
Just released https://github.com/buger/gor/releases/tag/v0.15.1
