### ISSUE TITLE
Is there any way to get real client IP

### ISSUE THREAD

**Issue by minminmsn** [buger/gor#367]
hello , Is there any way to get real client IP

the commond
 ./gor --input-raw em1:80 --output-http http://172.17.2.254:80   -input-raw-realip-header X-Real-IP
Version: v0.15.1

the access log
192.168.0.188 - - [21/Sep/2016:10:30:40 +0800] "GET /webapi/user/login.json HTTP/1.1" 404 576 "-"  "172.17.2.254" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 2.0.50727; InfoPath.1)" "-"
192.168.0.188 - - [21/Sep/2016:10:30:41 +0800] "GET /webapi/user/register.json HTTP/1.1" 404 576 "-"  "172.17.2.254" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 2.0.50727; InfoPath.1)" "-"

**Comment by buger** [comment]
Hello! Access log will always show you IP address of the current client, in the case of Gor, IP of the machine where it was running. It is a common problem, similar when using proxies or load balancers, and typical way to solve it is adding new custom HTTP header, which further you need to use inside your app. In the case of Gor, the command above adds new "X-Real-IP" header to all HTTP payloads.

Thank you!
