### ISSUE TITLE
Exception in GOR

### ISSUE THREAD

**Issue by pmittal1982** [buger/gor#373]
I get the following exception after sometime when running the gor

mac-6590:Downloads 6590$ sudo ./gor --input-raw :8080 --output-stdout
Password:
Version: v0.15.1

panic: runtime error: index out of range

goroutine 34 [running]:
panic(0x4500e40, 0xc820012060)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/buger/gor/raw_socket_listener.(_Listener).readPcap.func1(0xc820156000, 0xc821200190, 0xc82120a000, 0x4, 0x4, 0xc821200174, 0xc821200000, 0x3, 0x0, 0x0, ...)
    /Users/buger/Documents/work/go/src/github.com/buger/gor/raw_socket_listener/listener.go:473 +0x1cf6
created by github.com/buger/gor/raw_socket_listener.(_Listener).readPcap
    /Users/buger/Documents/work/go/src/github.com/buger/gor/raw_socket_listener/listener.go:532 +0x328

**Comment by buger** [comment]
Hello! I think you hit a bug, pls try this binaries:
[gor_fix_tpc_truncated_packet_mac.tar.gz](https://github.com/buger/gor/files/522333/gor_fix_tpc_truncated_packet_mac.tar.gz)
[gor_fix_tpc_truncated_packet_x64.tar.gz](https://github.com/buger/gor/files/522334/gor_fix_tpc_truncated_packet_x64.tar.gz)

**Comment by buger** [comment]
I'm going to close this, feel free to re-open if this build did not helped.
