### ISSUE TITLE
Get gor to honour the umask on file creation

### ISSUE THREAD

**Issue by piersharding** [buger/gor#378]
Hi -

Would it be possible to get gor to honour the umask on file creation?  The mask is set to 0660 here https://github.com/buger/gor/blob/967c380dc3ca1a96c6cbabd6296b0656a6546016/output_file.go#L178 , but according to this post http://stackoverflow.com/questions/23842247/reading-default-filemode-when-using-os-o-create 0666 should enable a locally set umask to work?

Thanks,
Piers.

**Comment by piersharding** [comment]
Please ignore this.  Solved by setting the group on the process.

Cheers,
Piers Harding,

**Comment by buger** [comment]
Cool! :)

But idea behind 666 probably make sense.
