### ISSUE TITLE
--output-http-stats does nothing unless --stats is also specified

### ISSUE THREAD

**Issue by salty-horse** [buger/gor#382]
Using 0.15.1

The flag --output-http-stats prints nothing unless the --stats flag is also specified.
This is very unintuitive, and doesn't seem intentional.

If this is intentional, it should be mentioned in the --help output, and also in the [Troubleshooting wiki](https://github.com/buger/gor/wiki/Troubleshooting) page.

**Comment by buger** [comment]
Yes, it definitely not user-friendly. I hope stats part to be completely rewritten in next releases.
