### ISSUE TITLE
Don't append port to Host when using HTTPS

### ISSUE THREAD

**Issue by salty-horse** [buger/gor#383]
Tested using 0.15.1, but I think it's relevant to master.

When `--output-http` points to HTTPS, Gor appends the ":443" port to the Host header.
This is unexpected. I can't find a reference in any standards, but browsers and various command line tools don't send it, and web servers don't expect it.

For example, here's curl's exception for HTTP and HTTPS: https://github.com/curl/curl/blob/0649433/lib/http.c#L2024

This condition in `http_client.go` line 64 should also check for "https":
```go
if u.Scheme != "http" {
    u.Host += ":" + defaultPorts[u.Scheme]
}
```

**Comment by buger** [comment]
Should be fixed in master, thank you for the report!
