### ISSUE TITLE
Looping Gor Dump  & Authentication

### ISSUE THREAD

**Issue by stripathi669** [buger/gor#386]
Suppose I create a small recording of my production traffic.

Can I put this dump on a loop forever?

2. Suppose my test server require Authentication header. But prod doesn't. Anyway to add that to outgoing requests?

**Comment by buger** [comment]
Hello!

1) You can loop requests using `--input-file-loop` https://github.com/buger/gor/wiki/Saving-and-Replaying-from-file#looping-files-for-replaying-indefinitely

2) If you are talking about basic http auth, adding header like this should work: `--http-header "Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l"` (you can generate base64 string from console like this: `printf Aladdin:OpenSesame | base64`)

Hope it helps!

**Comment by stripathi669** [comment]
Yeah. Thanks. This helps.
