### ISSUE TITLE
Gor stuck in request loop if same port

### ISSUE THREAD

**Issue by nenadstojanovikj** [buger/gor#391]
`Gor version 0.15.1`

I saw this fixed here: #292 but it's not working on my machine.

I have Gor running in a docker container which has `php-fpm` application running on port `80`. Whenever I make request to my application, Gor replicates it successfully, but keeps looping forever. 

This is the command i'm using to run Gor
`gor --input-raw :80 --input-raw-track-response --output-http http://localhost --output-stdout`

Let me know if you need more information.

**Comment by buger** [comment]
Hello! Well, it may be connected to how docker initializes its network interface, and maybe inside docker container it all goes through localhost loopback. 

I suggest making 2 tests. First, specify direct IP in `--input-raw`.

Second, try to run Gor in a separate container, which monitors first one with your app. It should be possible to know direct port of the container via `docker inspect`, smth like: `docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}' $INSTANCE_ID`

**Comment by nenadstojanovikj** [comment]
Okay, the first solution worked! I had to put the container's IP there, so the command looked like
`gor --input-raw 172.19.0.7:80 --input-raw-track-response --output-http http://localhost --output-stdout`. Thank you for the help!

**Comment by buger** [comment]
👍
