### ISSUE TITLE
Failed to start Sarama(Kafka) producer

### ISSUE THREAD

**Issue by ylegat** [buger/gor#397]
Since merge of pull request 719e9b8e563ab20bbd862f448674e41e3c3e9257, the execution of gor exit immediately with the following fatal error:
```
2016/12/01 14:07:25 Failed to start Sarama(Kafka) producer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

**Comment by oivoodoo** [comment]
Hi @ylegat . Sorry for that. Going to make the new pull request to fix this behaviour.

**Comment by ylegat** [comment]
@oivoodoo Those things happen ;)

**Comment by buger** [comment]
Should be fixed now
