### ISSUE TITLE
With latest release 'v0.15.1_x64' totally cannot replay request to remote Node.js express server

### ISSUE THREAD

**Issue by leonard-sxy** [buger/gor#399]
first, very great job, but it seems i cannot get it work.

I run with the following command:
```
sudo ./gor --input-raw :7000 --output-http http://10.0.2.8:7000
```
then got nothing on the server `10.0.2.8:7000`

If in run `./gor --input-raw-track-response :7000 --output-stdout`, then i do can get the request in the stdout.

and if i run `./gor --input-raw :7000 --output-file requests.log` i also can see the requests in the file.

but with command `./gor --input-file requests.gor --output-http "http://10.0.2.8:7000"` still cannot replay to server `10.0.2.8:7000`

and i see in the wiki doc

> It will record and replay traffic from the same machine. However, it is possible to use Aggregator-forwarder setup, when Gor on your web machines forward traffic to Gor aggregator instance running on the separate server.

but totally don't have any idea how to do this, can someone point me the way, thanks.

**Comment by leonard-sxy** [comment]
sorry, thanks again for this very great job, it is my fault, closing the issue.

**Comment by buger** [comment]
This was quick :) 

No problem, feel free to ask any question.
