### ISSUE TITLE
Replay process can not tee some request with error "Can not parse request"

### ISSUE THREAD

**Issue by TigerMee** [buger/gor#71]
In my case, I use gor(0.7.0) like:
sudo gor --input-raw :80 --output-http xxxx:80

However, about 20% request can not be transferred. The error is "Can not parse request". I want to figure out why this happens. One of the error log is:

2014/01/16 10:15:29 Can not parse request jUyMEhlYXRlcnMlMjUyMEdlbmVyYWwtXy1ob3Qrd2F0ZXIrdGFuayUyNnVybCU1YiU1ZCUzZGh0dHAlMjUzQSUyNTJGJTI1MkZ3d3cubG93ZXMuY29tJTI1MkZIZWF0aW5nLUNvb2xpbmclMjUyRldhdGVyLUhlYXRlcnMlMjUyRl8lMjUyRk4tMXoxMW9uZyUyNTJGcGwlMjUzRnJwcCUyNTNEMjQqCTE5MjQwODE3NTILMTEwNzUyNTEyNjA4ggJAAkhSUIYXWANhDonW5e+50D9oAHBSeFKBAYXrUbgehfc/iQE9CtejcD3qP5ABAJgBBAqQBQoZQS5PLiBTbWl0aCBIeWJyaWQgSGVhdGVycxJGSGlnaCBFZmZpZWNpZW5jeSBBLk8uIFNtaXRoIEh5YnJpZCBXYXRlciBIZWF0ZXJzLiBGaW5kIGEgRGVhbGVyIE9ubGluZRoTaHR0cDovL2hvdHdhdGVyLmNvbSLHA2h0dHA6Ly8yMDgxOTY4LnIubXNuLmNvbS8/bGQ9OHZkeFFBRW43WTZXSUhuY2t4UUgtWWd6VlVDVXdjUG12dnpSQVJaaXV5Z0xDa0lFQ1pJNExNaEVDbU1Yalh5UHBKckxtenN3RmFOeG9 malformed HTTP request "jUyMEhlYXRlcnMlMjUyMEdlbmVyYWwtXy1ob3Qrd2F0ZXIrdGFuayUyNnVybCU1YiU1ZCUzZGh0dHAlMjUzQSUyNTJGJTI1MkZ3d3cubG93ZXMuY29tJTI1MkZIZWF0aW5nLUNvb2xpbmclMjUyRldhdGVyLUhlYXRlcnMlMjUyRl8lMjUyRk4tMXoxMW9uZyUyNTJGcGwlMjUzRnJwcCUyNTNEMjQqCTE5MjQwODE3NTILMTEwNzUyNTEyNjA4ggJAAkhSUIYXWANhDonW5e+50D9oAHBSeFKBAYXrUbgehfc/iQE9CtejcD3qP5ABAJgBBAqQBQoZQS5PLiBTbWl0aCBIeWJyaWQgSGVhdGVycxJGSGlnaCBFZmZpZWNpZW5jeSBBLk8uIFNtaXRoIEh5YnJpZCBXYXRlciBIZWF0ZXJzLiBGaW5kIGEgRGVhbGVyIE9ubGluZRoTaHR0cDovL2hvdHdhdGVyLmNvbSLHA2h0dHA6Ly8yMDgxOTY4LnIubXNuLmNvbS8/bGQ9OHZkeFFBRW43WTZXSUhuY2t4UUgtWWd6VlVDVXdjUG12dnpSQVJaaXV5Z0xDa0lFQ1pJNExNaEVDbU1Yalh5UHBKckxtenN3RmFOeG9"

**Comment by buger** [comment]
@stephencurran @TigerMee well, it took a while, but now it should fixed by #158
