### ISSUE TITLE
Gor can't correctly forward POST request including "Expect: 100-continue"

### ISSUE THREAD

**Issue by Dieken** [buger/gor#77]
$ curl 'http://xxxx/'  -d @some-file -v

cURL sends normal HTTP headers including "Content-Length: nnnnn" and extra HTTP header "Expect: 100-continue" but empty request body,  the http server responses
"100 Continue" then cURL sends the request body.

This is valid HTTP request and I verified the http server feature in Go 1.2 net/http package can handle it correctly,  but Gor fails,  its input-http plugin wrongly thinks the empty http body is invalid.

**Comment by buger** [comment]
Fixed by #158

**Comment by buger** [comment]
@Dieken happy to announce that keep-alive is supported in just released  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) version (and lot of 100-continue fixes as well).
